# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_evidence_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEvidenceWizard(object):
    def setupUi(self, AddEvidenceWizard):
        AddEvidenceWizard.setObjectName("AddEvidenceWizard")
        AddEvidenceWizard.resize(800, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AddEvidenceWizard)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stepsFrame = QtWidgets.QFrame(AddEvidenceWizard)
        self.stepsFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.stepsFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.stepsFrame.setStyleSheet("QFrame {\n"
"    background-color: #f8f9fa;\n"
"    border-right: 1px solid #dee2e6;\n"
"}")
        self.stepsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stepsFrame.setObjectName("stepsFrame")
        self.stepsLayout = QtWidgets.QVBoxLayout(self.stepsFrame)
        self.stepsLayout.setContentsMargins(20, 30, 20, 30)
        self.stepsLayout.setSpacing(10)
        self.stepsLayout.setObjectName("stepsLayout")
        self.stepsHeaderLabel = QtWidgets.QLabel(self.stepsFrame)
        self.stepsHeaderLabel.setStyleSheet("font-size: 16px;\n"
"font-weight: bold;\n"
"color: #2d3748;\n"
"margin-bottom: 10px;")
        self.stepsHeaderLabel.setObjectName("stepsHeaderLabel")
        self.stepsLayout.addWidget(self.stepsHeaderLabel)
        self.step1Label = QtWidgets.QLabel(self.stepsFrame)
        self.step1Label.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #4a5568;\n"
"    padding: 8px;\n"
"    border-radius: 4px;\n"
"    margin: 2px 0;\n"
"}")
        self.step1Label.setObjectName("step1Label")
        self.stepsLayout.addWidget(self.step1Label)
        self.step2Label = QtWidgets.QLabel(self.stepsFrame)
        self.step2Label.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #4a5568;\n"
"    padding: 8px;\n"
"    border-radius: 4px;\n"
"    margin: 2px 0;\n"
"}")
        self.step2Label.setObjectName("step2Label")
        self.stepsLayout.addWidget(self.step2Label)
        self.step3Label = QtWidgets.QLabel(self.stepsFrame)
        self.step3Label.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #4a5568;\n"
"    padding: 8px;\n"
"    border-radius: 4px;\n"
"    margin: 2px 0;\n"
"}")
        self.step3Label.setObjectName("step3Label")
        self.stepsLayout.addWidget(self.step3Label)
        self.step4Label = QtWidgets.QLabel(self.stepsFrame)
        self.step4Label.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #4a5568;\n"
"    padding: 8px;\n"
"    border-radius: 4px;\n"
"    margin: 2px 0;\n"
"}")
        self.step4Label.setObjectName("step4Label")
        self.stepsLayout.addWidget(self.step4Label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.stepsLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.stepsFrame)
        self.contentFrame = QtWidgets.QFrame(AddEvidenceWizard)
        self.contentFrame.setStyleSheet("QFrame { background-color: white; }")
        self.contentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentFrame.setObjectName("contentFrame")
        self.contentLayout = QtWidgets.QVBoxLayout(self.contentFrame)
        self.contentLayout.setContentsMargins(30, 30, 30, 20)
        self.contentLayout.setSpacing(20)
        self.contentLayout.setObjectName("contentLayout")
        self.headerFrame = QtWidgets.QFrame(self.contentFrame)
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setObjectName("headerFrame")
        self.headerLayout = QtWidgets.QVBoxLayout(self.headerFrame)
        self.headerLayout.setContentsMargins(0, 0, 0, 0)
        self.headerLayout.setSpacing(5)
        self.headerLayout.setObjectName("headerLayout")
        self.titleLabel = QtWidgets.QLabel(self.headerFrame)
        self.titleLabel.setStyleSheet("font-size: 18px;\n"
"font-weight: bold;\n"
"color: #2d3748;")
        self.titleLabel.setObjectName("titleLabel")
        self.headerLayout.addWidget(self.titleLabel)
        self.descriptionLabel = QtWidgets.QLabel(self.headerFrame)
        self.descriptionLabel.setStyleSheet("font-size: 12px;\n"
"color: #718096;")
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.headerLayout.addWidget(self.descriptionLabel)
        self.contentLayout.addWidget(self.headerFrame)
        self.stackedWidget = QtWidgets.QStackedWidget(self.contentFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.step1Widget = QtWidgets.QWidget()
        self.step1Widget.setObjectName("step1Widget")
        self.step1Layout = QtWidgets.QVBoxLayout(self.step1Widget)
        self.step1Layout.setSpacing(15)
        self.step1Layout.setObjectName("step1Layout")
        self.importModeRadio = QtWidgets.QRadioButton(self.step1Widget)
        self.importModeRadio.setStyleSheet("font-size: 14px; padding: 10px;")
        self.importModeRadio.setChecked(True)
        self.importModeRadio.setObjectName("importModeRadio")
        self.step1Layout.addWidget(self.importModeRadio)
        self.collectModeRadio = QtWidgets.QRadioButton(self.step1Widget)
        self.collectModeRadio.setStyleSheet("font-size: 14px; padding: 10px;")
        self.collectModeRadio.setObjectName("collectModeRadio")
        self.step1Layout.addWidget(self.collectModeRadio)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step1Layout.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.step1Widget)
        self.step2Widget = QtWidgets.QWidget()
        self.step2Widget.setObjectName("step2Widget")
        self.step2Layout = QtWidgets.QVBoxLayout(self.step2Widget)
        self.step2Layout.setSpacing(15)
        self.step2Layout.setObjectName("step2Layout")
        self.volatileTypeRadio = QtWidgets.QRadioButton(self.step2Widget)
        self.volatileTypeRadio.setStyleSheet("font-size: 14px; padding: 10px;")
        self.volatileTypeRadio.setChecked(True)
        self.volatileTypeRadio.setObjectName("volatileTypeRadio")
        self.step2Layout.addWidget(self.volatileTypeRadio)
        self.nonvolatileTypeRadio = QtWidgets.QRadioButton(self.step2Widget)
        self.nonvolatileTypeRadio.setStyleSheet("font-size: 14px; padding: 10px;")
        self.nonvolatileTypeRadio.setObjectName("nonvolatileTypeRadio")
        self.step2Layout.addWidget(self.nonvolatileTypeRadio)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step2Layout.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.step2Widget)
        self.step3Widget = QtWidgets.QWidget()
        self.step3Widget.setObjectName("step3Widget")
        self.step3Layout = QtWidgets.QVBoxLayout(self.step3Widget)
        self.step3Layout.setSpacing(15)
        self.step3Layout.setObjectName("step3Layout")
        self.importSourceFrame = QtWidgets.QFrame(self.step3Widget)
        self.importSourceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.importSourceFrame.setObjectName("importSourceFrame")
        self.importSourceLayout = QtWidgets.QVBoxLayout(self.importSourceFrame)
        self.importSourceLayout.setObjectName("importSourceLayout")
        self.label = QtWidgets.QLabel(self.importSourceFrame)
        self.label.setObjectName("label")
        self.importSourceLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.importSourceFrame)
        self.label_2.setStyleSheet("color: #666; font-size: 11px; font-style: italic; margin-bottom: 5px;")
        self.label_2.setObjectName("label_2")
        self.importSourceLayout.addWidget(self.label_2)
        self.fileListWidget = QtWidgets.QTableWidget(self.importSourceFrame)
        self.fileListWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.fileListWidget.setStyleSheet("QTableWidget {\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 4px;\n"
"    background-color: white;\n"
"    font-size: 12px;\n"
"    gridline-color: #e9ecef;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #f1f3f4;\n"
"    color: black;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #e3f2fd;\n"
"    color: black;\n"
"}\n"
"QTableWidget::item:focus {\n"
"    background-color: #fff3cd;\n"
"    border: 1px solid #ffc107;\n"
"    border-radius: 2px;\n"
"    color: black;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f8f9fa;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 2px solid #dee2e6;\n"
"    font-weight: bold;\n"
"    color: #495057;\n"
"}\n"
"QTableWidget QLineEdit {\n"
"    padding: 6px 10px;\n"
"    border: 1px solid #007bff;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    font-size: 13px;\n"
"    margin: 2px;\n"
"    color: black;\n"
"}")
        self.fileListWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.fileListWidget.setObjectName("fileListWidget")
        self.fileListWidget.setColumnCount(3)
        self.fileListWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fileListWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileListWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileListWidget.setHorizontalHeaderItem(2, item)
        self.importSourceLayout.addWidget(self.fileListWidget)
        self.fileButtonFrame = QtWidgets.QFrame(self.importSourceFrame)
        self.fileButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fileButtonFrame.setObjectName("fileButtonFrame")
        self.fileButtonLayout = QtWidgets.QHBoxLayout(self.fileButtonFrame)
        self.fileButtonLayout.setContentsMargins(0, 10, 0, 0)
        self.fileButtonLayout.setObjectName("fileButtonLayout")
        self.addFilesBtn = QtWidgets.QPushButton(self.fileButtonFrame)
        self.addFilesBtn.setObjectName("addFilesBtn")
        self.fileButtonLayout.addWidget(self.addFilesBtn)
        self.addFoldersBtn = QtWidgets.QPushButton(self.fileButtonFrame)
        self.addFoldersBtn.setObjectName("addFoldersBtn")
        self.fileButtonLayout.addWidget(self.addFoldersBtn)
        self.removeFileBtn = QtWidgets.QPushButton(self.fileButtonFrame)
        self.removeFileBtn.setObjectName("removeFileBtn")
        self.fileButtonLayout.addWidget(self.removeFileBtn)
        self.clearAllBtn = QtWidgets.QPushButton(self.fileButtonFrame)
        self.clearAllBtn.setObjectName("clearAllBtn")
        self.fileButtonLayout.addWidget(self.clearAllBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.fileButtonLayout.addItem(spacerItem3)
        self.importSourceLayout.addWidget(self.fileButtonFrame)
        self.step3Layout.addWidget(self.importSourceFrame)
        self.collectSourceFrame = QtWidgets.QFrame(self.step3Widget)
        self.collectSourceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.collectSourceFrame.setVisible(False)
        self.collectSourceFrame.setObjectName("collectSourceFrame")
        self.collectSourceLayout = QtWidgets.QVBoxLayout(self.collectSourceFrame)
        self.collectSourceLayout.setObjectName("collectSourceLayout")
        self.volatileInfoLabel = QtWidgets.QLabel(self.collectSourceFrame)
        self.volatileInfoLabel.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: #2d3748;\n"
"    background-color: #f8f9fa;\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 8px;\n"
"    padding: 20px;\n"
"    line-height: 1.5;\n"
"}")
        self.volatileInfoLabel.setWordWrap(True)
        self.volatileInfoLabel.setObjectName("volatileInfoLabel")
        self.collectSourceLayout.addWidget(self.volatileInfoLabel)
        self.startVolatileBtn = QtWidgets.QPushButton(self.collectSourceFrame)
        self.startVolatileBtn.setStyleSheet("QPushButton {\n"
"    background-color: #3182ce;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 15px 30px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2c5aa0;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #e2e8f0;\n"
"    color: #a0aec0;\n"
"}")
        self.startVolatileBtn.setObjectName("startVolatileBtn")
        self.collectSourceLayout.addWidget(self.startVolatileBtn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.collectSourceLayout.addItem(spacerItem4)
        self.step3Layout.addWidget(self.collectSourceFrame)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step3Layout.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.step3Widget)
        self.step4Widget = QtWidgets.QWidget()
        self.step4Widget.setObjectName("step4Widget")
        self.step4Layout = QtWidgets.QVBoxLayout(self.step4Widget)
        self.step4Layout.setSpacing(15)
        self.step4Layout.setObjectName("step4Layout")
        self.importConfigFrame = QtWidgets.QFrame(self.step4Widget)
        self.importConfigFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.importConfigFrame.setObjectName("importConfigFrame")
        self.importConfigLayout = QtWidgets.QVBoxLayout(self.importConfigFrame)
        self.importConfigLayout.setObjectName("importConfigLayout")
        self.processingGroup = QtWidgets.QGroupBox(self.importConfigFrame)
        self.processingGroup.setObjectName("processingGroup")
        self.processingGroupLayout = QtWidgets.QVBoxLayout(self.processingGroup)
        self.processingGroupLayout.setObjectName("processingGroupLayout")
        self.calculateHashCheck = QtWidgets.QCheckBox(self.processingGroup)
        self.calculateHashCheck.setStyleSheet("font-size: 12px; padding: 5px;")
        self.calculateHashCheck.setChecked(True)
        self.calculateHashCheck.setObjectName("calculateHashCheck")
        self.processingGroupLayout.addWidget(self.calculateHashCheck)
        self.verifyIntegrityCheck = QtWidgets.QCheckBox(self.processingGroup)
        self.verifyIntegrityCheck.setStyleSheet("font-size: 12px; padding: 5px;")
        self.verifyIntegrityCheck.setChecked(True)
        self.verifyIntegrityCheck.setObjectName("verifyIntegrityCheck")
        self.processingGroupLayout.addWidget(self.verifyIntegrityCheck)
        self.createBackupCheck = QtWidgets.QCheckBox(self.processingGroup)
        self.createBackupCheck.setStyleSheet("font-size: 12px; padding: 5px;")
        self.createBackupCheck.setObjectName("createBackupCheck")
        self.processingGroupLayout.addWidget(self.createBackupCheck)
        self.importConfigLayout.addWidget(self.processingGroup)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.importConfigLayout.addItem(spacerItem6)
        self.step4Layout.addWidget(self.importConfigFrame)
        self.collectConfigFrame = QtWidgets.QFrame(self.step4Widget)
        self.collectConfigFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.collectConfigFrame.setVisible(False)
        self.collectConfigFrame.setObjectName("collectConfigFrame")
        self.collectConfigLayout = QtWidgets.QVBoxLayout(self.collectConfigFrame)
        self.collectConfigLayout.setObjectName("collectConfigLayout")
        self.nonvolatileInfoLabel = QtWidgets.QLabel(self.collectConfigFrame)
        self.nonvolatileInfoLabel.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: #2d3748;\n"
"    background-color: #f8f9fa;\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 8px;\n"
"    padding: 20px;\n"
"    line-height: 1.5;\n"
"}")
        self.nonvolatileInfoLabel.setWordWrap(True)
        self.nonvolatileInfoLabel.setObjectName("nonvolatileInfoLabel")
        self.collectConfigLayout.addWidget(self.nonvolatileInfoLabel)
        self.startNonvolatileBtn = QtWidgets.QPushButton(self.collectConfigFrame)
        self.startNonvolatileBtn.setStyleSheet("QPushButton {\n"
"    background-color: #3182ce;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 15px 30px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2c5aa0;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #e2e8f0;\n"
"    color: #a0aec0;\n"
"}")
        self.startNonvolatileBtn.setObjectName("startNonvolatileBtn")
        self.collectConfigLayout.addWidget(self.startNonvolatileBtn)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.collectConfigLayout.addItem(spacerItem7)
        self.step4Layout.addWidget(self.collectConfigFrame)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.step4Layout.addItem(spacerItem8)
        self.stackedWidget.addWidget(self.step4Widget)
        self.contentLayout.addWidget(self.stackedWidget)
        self.buttonFrame = QtWidgets.QFrame(self.contentFrame)
        self.buttonFrame.setStyleSheet("QFrame {\n"
"    border-top: 1px solid #dee2e6;\n"
"    background-color: #f8f9fa;\n"
"}")
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setObjectName("buttonFrame")
        self.buttonLayout = QtWidgets.QHBoxLayout(self.buttonFrame)
        self.buttonLayout.setContentsMargins(30, 15, 30, 15)
        self.buttonLayout.setObjectName("buttonLayout")
        self.backBtn = QtWidgets.QPushButton(self.buttonFrame)
        self.backBtn.setEnabled(False)
        self.backBtn.setMinimumSize(QtCore.QSize(80, 0))
        self.backBtn.setStyleSheet("QPushButton {\n"
"    background-color: #4299e1;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3182ce;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #e2e8f0;\n"
"    color: #a0aec0;\n"
"}")
        self.backBtn.setObjectName("backBtn")
        self.buttonLayout.addWidget(self.backBtn)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem9)
        self.nextBtn = QtWidgets.QPushButton(self.buttonFrame)
        self.nextBtn.setMinimumSize(QtCore.QSize(80, 0))
        self.nextBtn.setStyleSheet("QPushButton {\n"
"    background-color: #4299e1;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3182ce;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #e2e8f0;\n"
"    color: #a0aec0;\n"
"}")
        self.nextBtn.setObjectName("nextBtn")
        self.buttonLayout.addWidget(self.nextBtn)
        self.finishBtn = QtWidgets.QPushButton(self.buttonFrame)
        self.finishBtn.setMinimumSize(QtCore.QSize(80, 0))
        self.finishBtn.setStyleSheet("QPushButton {\n"
"    background-color: #4299e1;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3182ce;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #e2e8f0;\n"
"    color: #a0aec0;\n"
"}")
        self.finishBtn.setVisible(False)
        self.finishBtn.setObjectName("finishBtn")
        self.buttonLayout.addWidget(self.finishBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.buttonFrame)
        self.cancelBtn.setMinimumSize(QtCore.QSize(80, 0))
        self.cancelBtn.setStyleSheet("QPushButton {\n"
"    background-color: #e2e8f0;\n"
"    color: #4a5568;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #cbd5e0;\n"
"}")
        self.cancelBtn.setObjectName("cancelBtn")
        self.buttonLayout.addWidget(self.cancelBtn)
        self.contentLayout.addWidget(self.buttonFrame)
        self.horizontalLayout.addWidget(self.contentFrame)

        self.retranslateUi(AddEvidenceWizard)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AddEvidenceWizard)

    def retranslateUi(self, AddEvidenceWizard):
        _translate = QtCore.QCoreApplication.translate
        AddEvidenceWizard.setWindowTitle(_translate("AddEvidenceWizard", "Add Evidence - Windows Forensic System"))
        self.stepsHeaderLabel.setText(_translate("AddEvidenceWizard", "Steps"))
        self.step1Label.setText(_translate("AddEvidenceWizard", "1. Select Mode Add Evidence"))
        self.step2Label.setText(_translate("AddEvidenceWizard", "2. Select Evidence Type"))
        self.step3Label.setText(_translate("AddEvidenceWizard", "3. Select Evidence Source"))
        self.step4Label.setText(_translate("AddEvidenceWizard", "4. Add Evidence Source"))
        self.titleLabel.setText(_translate("AddEvidenceWizard", "Select Mode Add Evidence"))
        self.descriptionLabel.setText(_translate("AddEvidenceWizard", "Choose how you want to add evidence to the case."))
        self.importModeRadio.setText(_translate("AddEvidenceWizard", "Import existing evidence files"))
        self.collectModeRadio.setText(_translate("AddEvidenceWizard", "Collect evidence from system"))
        self.volatileTypeRadio.setText(_translate("AddEvidenceWizard", "Volatile Data (Memory, Network, Processes, ...)"))
        self.nonvolatileTypeRadio.setText(_translate("AddEvidenceWizard", "Non-volatile Data (Disk, Files, Registry, ...)"))
        self.label.setText(_translate("AddEvidenceWizard", "Selected Evidence Files:"))
        self.label_2.setText(_translate("AddEvidenceWizard", "💡 Tip: Double-click on the \'Name\' column to edit individual evidence names"))
        item = self.fileListWidget.horizontalHeaderItem(0)
        item.setText(_translate("AddEvidenceWizard", "Type"))
        item = self.fileListWidget.horizontalHeaderItem(1)
        item.setText(_translate("AddEvidenceWizard", "Name"))
        item = self.fileListWidget.horizontalHeaderItem(2)
        item.setText(_translate("AddEvidenceWizard", "Path"))
        self.addFilesBtn.setText(_translate("AddEvidenceWizard", "Add Files"))
        self.addFoldersBtn.setText(_translate("AddEvidenceWizard", "Add Folders"))
        self.removeFileBtn.setText(_translate("AddEvidenceWizard", "Remove Selected"))
        self.clearAllBtn.setText(_translate("AddEvidenceWizard", "Clear All"))
        self.volatileInfoLabel.setText(_translate("AddEvidenceWizard", "Volatile data collection will gather:\n"
"\n"
"- Memory dump\n"
"- Running processes\n"
"- Network connections\n"
"- System information\n"
"- System time & uptime\n"
"\n"
"Click \'Start Volatile Collection\' to begin data collection.\n"
"This will open the volatile collection interface."))
        self.startVolatileBtn.setText(_translate("AddEvidenceWizard", "Start Volatile Collection"))
        self.processingGroup.setTitle(_translate("AddEvidenceWizard", "Processing Options"))
        self.calculateHashCheck.setText(_translate("AddEvidenceWizard", "Calculate file hashes (SHA-256)"))
        self.verifyIntegrityCheck.setText(_translate("AddEvidenceWizard", "Verify file integrity"))
        self.createBackupCheck.setText(_translate("AddEvidenceWizard", "Create backup copies"))
        self.nonvolatileInfoLabel.setText(_translate("AddEvidenceWizard", "Non-volatile data collection will gather:\n"
"\n"
"- Disk images\n"
"- File system artifacts\n"
"- Registry hives\n"
"- Event logs\n"
"- Browser artifacts\n"
"- System logs\n"
"\n"
"Click \'Start Non-volatile Collection\' to begin data collection.\n"
"This will open the non-volatile collection interface."))
        self.startNonvolatileBtn.setText(_translate("AddEvidenceWizard", "Start Non-volatile Collection"))
        self.backBtn.setText(_translate("AddEvidenceWizard", "< Back"))
        self.nextBtn.setText(_translate("AddEvidenceWizard", "Next >"))
        self.finishBtn.setText(_translate("AddEvidenceWizard", "Finish"))
        self.cancelBtn.setText(_translate("AddEvidenceWizard", "Cancel"))