# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/pages/create_case_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateCaseDialog(object):
    def setupUi(self, CreateCaseDialog):
        CreateCaseDialog.setObjectName("CreateCaseDialog")
        CreateCaseDialog.resize(549, 448)
        CreateCaseDialog.setStyleSheet("QDialog {\n"
"    background-color: #f8f9fa;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 8px;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 8px 0 8px;\n"
"    color: #495057;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #007bff;\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 12px 24px;\n"
"    border-radius: 6px;\n"
"    font-weight: 500;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085;\n"
"}\n"
"\n"
"QPushButton#createBtn {\n"
"    background-color: #28a745;\n"
"    font-size: 16px;\n"
"    padding: 15px 30px;\n"
"}\n"
"\n"
"QPushButton#createBtn:hover {\n"
"    background-color: #1e7e34;\n"
"}\n"
"\n"
"QPushButton#cancelBtn {\n"
"    background-color: #6c757d;\n"
"}\n"
"\n"
"QPushButton#cancelBtn:hover {\n"
"    background-color: #545b62;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid #ced4da;\n"
"    border-radius: 6px;\n"
"    padding: 12px 16px;\n"
"    font-size: 16px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #007bff;\n"
"    outline: 0;\n"
"    box-shadow: 0 0 0 0.2rem rgba(0,123,255,.25);\n"
"}\n"
"\n"
"QRadioButton {\n"
"    spacing: 8px;\n"
"    font-size: 14px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    border: 2px solid #ced4da;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid #007bff;\n"
"    border-radius: 10px;\n"
"    background-color: #007bff;\n"
"}\n"
"\n"
"QLabel#titleLabel {\n"
"    color: #343a40;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#subtitleLabel {\n"
"    color: #6c757d;\n"
"    font-size: 14px;\n"
"}")
        CreateCaseDialog.setModal(True)
        self.mainLayout = QtWidgets.QVBoxLayout(CreateCaseDialog)
        self.mainLayout.setContentsMargins(30, 30, 30, 30)
        self.mainLayout.setSpacing(20)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLabel = QtWidgets.QLabel(CreateCaseDialog)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(CreateCaseDialog)
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.mainLayout.addWidget(self.subtitleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem)
        self.inputLayout = QtWidgets.QVBoxLayout()
        self.inputLayout.setSpacing(8)
        self.inputLayout.setObjectName("inputLayout")
        self.caseNameLabel = QtWidgets.QLabel(CreateCaseDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.caseNameLabel.setFont(font)
        self.caseNameLabel.setObjectName("caseNameLabel")
        self.inputLayout.addWidget(self.caseNameLabel)
        self.caseNameEdit = QtWidgets.QLineEdit(CreateCaseDialog)
        self.caseNameEdit.setObjectName("caseNameEdit")
        self.inputLayout.addWidget(self.caseNameEdit)
        self.mainLayout.addLayout(self.inputLayout)
        self.pathLayout = QtWidgets.QVBoxLayout()
        self.pathLayout.setSpacing(8)
        self.pathLayout.setObjectName("pathLayout")
        self.pathLabel = QtWidgets.QLabel(CreateCaseDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pathLabel.setFont(font)
        self.pathLabel.setObjectName("pathLabel")
        self.pathLayout.addWidget(self.pathLabel)
        self.casePathEdit = QtWidgets.QLineEdit(CreateCaseDialog)
        self.casePathEdit.setReadOnly(True)
        self.casePathEdit.setStyleSheet("background-color: #f8f9fa; color: #6c757d;")
        self.casePathEdit.setObjectName("casePathEdit")
        self.pathLayout.addWidget(self.casePathEdit)
        self.mainLayout.addLayout(self.pathLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(16)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.cancelBtn = QtWidgets.QPushButton(CreateCaseDialog)
        self.cancelBtn.setObjectName("cancelBtn")
        self.buttonLayout.addWidget(self.cancelBtn)
        self.createBtn = QtWidgets.QPushButton(CreateCaseDialog)
        self.createBtn.setObjectName("createBtn")
        self.buttonLayout.addWidget(self.createBtn)
        self.mainLayout.addLayout(self.buttonLayout)

        self.retranslateUi(CreateCaseDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateCaseDialog)

    def retranslateUi(self, CreateCaseDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateCaseDialog.setWindowTitle(_translate("CreateCaseDialog", "Tạo Case Mới"))
        self.titleLabel.setText(_translate("CreateCaseDialog", "🆕 Tạo Case Mới"))
        self.subtitleLabel.setText(_translate("CreateCaseDialog", "Nhập tên case để bắt đầu điều tra"))
        self.caseNameLabel.setText(_translate("CreateCaseDialog", "Tên Case:"))
        self.caseNameEdit.setPlaceholderText(_translate("CreateCaseDialog", "VD: Điều tra máy tính nhân viên A"))
        self.pathLabel.setText(_translate("CreateCaseDialog", "Đường dẫn lưu trữ:"))
        self.casePathEdit.setPlaceholderText(_translate("CreateCaseDialog", "Đường dẫn sẽ được tạo tự động..."))
        self.cancelBtn.setText(_translate("CreateCaseDialog", "Hủy"))
        self.createBtn.setText(_translate("CreateCaseDialog", "✅ Tạo Case"))
