# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/pages/edit_case_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditCaseDialog(object):
    def setupUi(self, EditCaseDialog):
        EditCaseDialog.setObjectName("EditCaseDialog")
        EditCaseDialog.resize(549, 448)
        EditCaseDialog.setStyleSheet("QDialog {\n"
"    background-color: #f8f9fa;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 8px;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 8px 0 8px;\n"
"    color: #495057;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #007bff;\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 12px 24px;\n"
"    border-radius: 6px;\n"
"    font-weight: 500;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085;\n"
"}\n"
"\n"
"QPushButton#saveBtn {\n"
"    background-color: #28a745;\n"
"    font-size: 16px;\n"
"    padding: 15px 30px;\n"
"}\n"
"\n"
"QPushButton#saveBtn:hover {\n"
"    background-color: #1e7e34;\n"
"}\n"
"\n"
"QPushButton#cancelBtn {\n"
"    background-color: #6c757d;\n"
"}\n"
"\n"
"QPushButton#cancelBtn:hover {\n"
"    background-color: #545b62;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid #ced4da;\n"
"    border-radius: 6px;\n"
"    padding: 12px 16px;\n"
"    font-size: 16px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #007bff;\n"
"    outline: 0;\n"
"    box-shadow: 0 0 0 0.2rem rgba(0,123,255,.25);\n"
"}\n"
"\n"
"QLineEdit:read-only {\n"
"    background-color: #f8f9fa;\n"
"    color: #6c757d;\n"
"}\n"
"\n"
"\n"
"QComboBox {\n"
"    border: 2px solid #ced4da;\n"
"    border-radius: 6px;\n"
"    padding: 12px 16px;\n"
"    font-size: 14px;\n"
"    background-color: white;\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: #007bff;\n"
"}\n"
"\n"
"QLabel#titleLabel {\n"
"    color: #343a40;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#subtitleLabel {\n"
"    color: #6c757d;\n"
"    font-size: 14px;\n"
"}")
        EditCaseDialog.setModal(True)
        self.mainLayout = QtWidgets.QVBoxLayout(EditCaseDialog)
        self.mainLayout.setContentsMargins(30, 30, 30, 30)
        self.mainLayout.setSpacing(20)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLabel = QtWidgets.QLabel(EditCaseDialog)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(EditCaseDialog)
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.mainLayout.addWidget(self.subtitleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem)
        self.inputLayout = QtWidgets.QVBoxLayout()
        self.inputLayout.setSpacing(12)
        self.inputLayout.setObjectName("inputLayout")
        self.caseNameLabel = QtWidgets.QLabel(EditCaseDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.caseNameLabel.setFont(font)
        self.caseNameLabel.setObjectName("caseNameLabel")
        self.inputLayout.addWidget(self.caseNameLabel)
        self.caseNameEdit = QtWidgets.QLineEdit(EditCaseDialog)
        self.caseNameEdit.setObjectName("caseNameEdit")
        self.inputLayout.addWidget(self.caseNameEdit)
        self.statusLabel = QtWidgets.QLabel(EditCaseDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.inputLayout.addWidget(self.statusLabel)
        self.statusCombo = QtWidgets.QComboBox(EditCaseDialog)
        self.statusCombo.setObjectName("statusCombo")
        self.statusCombo.addItem("")
        self.statusCombo.addItem("")
        self.statusCombo.addItem("")
        self.statusCombo.addItem("")
        self.inputLayout.addWidget(self.statusCombo)
        self.pathLabel = QtWidgets.QLabel(EditCaseDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pathLabel.setFont(font)
        self.pathLabel.setObjectName("pathLabel")
        self.inputLayout.addWidget(self.pathLabel)
        self.casePathEdit = QtWidgets.QLineEdit(EditCaseDialog)
        self.casePathEdit.setReadOnly(True)
        self.casePathEdit.setStyleSheet("background-color: #f8f9fa; color: #6c757d;")
        self.casePathEdit.setObjectName("casePathEdit")
        self.inputLayout.addWidget(self.casePathEdit)
        self.mainLayout.addLayout(self.inputLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(16)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.cancelBtn = QtWidgets.QPushButton(EditCaseDialog)
        self.cancelBtn.setObjectName("cancelBtn")
        self.buttonLayout.addWidget(self.cancelBtn)
        self.saveBtn = QtWidgets.QPushButton(EditCaseDialog)
        self.saveBtn.setObjectName("saveBtn")
        self.buttonLayout.addWidget(self.saveBtn)
        self.mainLayout.addLayout(self.buttonLayout)

        self.retranslateUi(EditCaseDialog)
        QtCore.QMetaObject.connectSlotsByName(EditCaseDialog)

    def retranslateUi(self, EditCaseDialog):
        _translate = QtCore.QCoreApplication.translate
        EditCaseDialog.setWindowTitle(_translate("EditCaseDialog", "Sửa Case"))
        self.titleLabel.setText(_translate("EditCaseDialog", "✏️ Sửa Case"))
        self.subtitleLabel.setText(_translate("EditCaseDialog", "Cập nhật thông tin case"))
        self.caseNameLabel.setText(_translate("EditCaseDialog", "Tên Case:"))
        self.caseNameEdit.setPlaceholderText(_translate("EditCaseDialog", "Nhập tên case..."))
        self.statusLabel.setText(_translate("EditCaseDialog", "Trạng thái:"))
        self.statusCombo.setItemText(0, _translate("EditCaseDialog", "OPEN"))
        self.statusCombo.setItemText(1, _translate("EditCaseDialog", "IN_PROGRESS"))
        self.statusCombo.setItemText(2, _translate("EditCaseDialog", "CLOSED"))
        self.statusCombo.setItemText(3, _translate("EditCaseDialog", "ARCHIVED"))
        self.pathLabel.setText(_translate("EditCaseDialog", "Đường dẫn lưu trữ:"))
        self.casePathEdit.setPlaceholderText(_translate("EditCaseDialog", "Đường dẫn case..."))
        self.cancelBtn.setText(_translate("EditCaseDialog", "Hủy"))
        self.saveBtn.setText(_translate("EditCaseDialog", "💾 Lưu thay đổi"))
