# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeDialog(object):
    def setupUi(self, WelcomeDialog):
        WelcomeDialog.setObjectName("WelcomeDialog")
        WelcomeDialog.resize(600, 450)
        WelcomeDialog.setMinimumSize(QtCore.QSize(600, 450))
        WelcomeDialog.setMaximumSize(QtCore.QSize(600, 450))
        WelcomeDialog.setStyleSheet("QDialog {\n"
"    background-color: #f8f9fa;\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #2d3748;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 8px;\n"
"    padding: 15px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #2d3748;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #edf2f7;\n"
"    border-color: #cbd5e0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e2e8f0;\n"
"}\n"
"\n"
"QPushButton#closeBtn {\n"
"    background-color: #e53e3e;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 20px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton#closeBtn:hover {\n"
"    background-color: #c53030;\n"
"}")
        
        # Main layout
        self.verticalLayout = QtWidgets.QVBoxLayout(WelcomeDialog)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Header
        self.headerLabel = QtWidgets.QLabel(WelcomeDialog)
        self.headerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headerLabel.setObjectName("headerLabel")
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.headerLabel.setFont(font)
        self.headerLabel.setText("Windows Forensic System")
        self.verticalLayout.addWidget(self.headerLabel)
        
        # Spacer - reduce space between title and options
        spacer1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacer1)
        
        # Options container
        self.optionsFrame = QtWidgets.QFrame(WelcomeDialog)
        self.optionsFrame.setObjectName("optionsFrame")
        self.optionsLayout = QtWidgets.QVBoxLayout(self.optionsFrame)
        self.optionsLayout.setSpacing(15)
        self.optionsLayout.setObjectName("optionsLayout")
        
        # New Case Button
        self.newCaseBtn = QtWidgets.QPushButton(self.optionsFrame)
        self.newCaseBtn.setMinimumSize(QtCore.QSize(0, 70))
        self.newCaseBtn.setObjectName("newCaseBtn")
        self.newCaseBtn.setText("📁 Tạo Case Mới")
        self.optionsLayout.addWidget(self.newCaseBtn)
        
        # Open Recent Case Button
        self.openRecentBtn = QtWidgets.QPushButton(self.optionsFrame)
        self.openRecentBtn.setMinimumSize(QtCore.QSize(0, 70))
        self.openRecentBtn.setObjectName("openRecentBtn")
        self.openRecentBtn.setText("📂 Mở Case Gần Đây")
        self.optionsLayout.addWidget(self.openRecentBtn)
        
        # Open Case Button
        self.openCaseBtn = QtWidgets.QPushButton(self.optionsFrame)
        self.openCaseBtn.setMinimumSize(QtCore.QSize(0, 70))
        self.openCaseBtn.setObjectName("openCaseBtn")
        self.openCaseBtn.setText("📋 Quản Lý Tất Cả Case")
        self.optionsLayout.addWidget(self.openCaseBtn)
        
        self.verticalLayout.addWidget(self.optionsFrame)
        
        # Spacer - reduce bottom space
        spacer2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacer2)
        
        # Bottom buttons
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        
        # Spacer left
        spacer3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacer3)
        
        # Close button
        self.closeBtn = QtWidgets.QPushButton(WelcomeDialog)
        self.closeBtn.setObjectName("closeBtn")
        self.closeBtn.setText("Đóng")
        self.buttonLayout.addWidget(self.closeBtn)
        
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(WelcomeDialog)
        QtCore.QMetaObject.connectSlotsByName(WelcomeDialog)

    def retranslateUi(self, WelcomeDialog):
        _translate = QtCore.QCoreApplication.translate
        WelcomeDialog.setWindowTitle(_translate("WelcomeDialog", "Wellcome")) 