# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(550, 750)
        LoginWindow.setMinimumSize(QtCore.QSize(550, 750))
        LoginWindow.setMaximumSize(QtCore.QSize(550, 750))
        LoginWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #2E86AB, stop:1 #A23B72);\n"
"}\n"
"QWidget#centralwidget {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #2E86AB, stop:1 #A23B72);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(50, 40, 50, 40)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo_frame = QtWidgets.QFrame(self.centralwidget)
        self.logo_frame.setStyleSheet("QFrame {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 15px;\n"
"    border: 2px solid rgba(255, 255, 255, 0.2);\n"
"}")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setObjectName("logo_frame")
        self.logo_layout = QtWidgets.QVBoxLayout(self.logo_frame)
        self.logo_layout.setContentsMargins(20, 20, 20, 20)
        self.logo_layout.setObjectName("logo_layout")
        self.title_label = QtWidgets.QLabel(self.logo_frame)
        self.title_label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 10px;\n"
"}")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.logo_layout.addWidget(self.title_label)
        self.subtitle_label = QtWidgets.QLabel(self.logo_frame)
        self.subtitle_label.setStyleSheet("QLabel {\n"
"    color: rgba(255, 255, 255, 0.8);\n"
"    font-size: 16px;\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}")
        self.subtitle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle_label.setObjectName("subtitle_label")
        self.logo_layout.addWidget(self.subtitle_label)
        self.verticalLayout.addWidget(self.logo_frame)
        self.login_frame = QtWidgets.QFrame(self.centralwidget)
        self.login_frame.setStyleSheet("QFrame {\n"
"    background-color: rgba(255, 255, 255, 0.95);\n"
"    border-radius: 15px;\n"
"    border: 2px solid rgba(255, 255, 255, 0.3);\n"
"}")
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setObjectName("login_frame")
        self.form_layout = QtWidgets.QVBoxLayout(self.login_frame)
        self.form_layout.setContentsMargins(40, 35, 40, 35)
        self.form_layout.setSpacing(18)
        self.form_layout.setObjectName("form_layout")
        self.username_label = QtWidgets.QLabel(self.login_frame)
        self.username_label.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.username_label.setObjectName("username_label")
        self.form_layout.addWidget(self.username_label)
        self.username_input = QtWidgets.QLineEdit(self.login_frame)
        self.username_input.setStyleSheet("QLineEdit {\n"
"    padding: 15px;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 8px;\n"
"    font-size: 16px;\n"
"    background-color: white;\n"
"    min-height: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #2E86AB;\n"
"}\n"
"QLineEdit::placeholder {\n"
"    color: #999;\n"
"    font-style: italic;\n"
"}")
        self.username_input.setObjectName("username_input")
        self.form_layout.addWidget(self.username_input)
        self.password_label = QtWidgets.QLabel(self.login_frame)
        self.password_label.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.password_label.setObjectName("password_label")
        self.form_layout.addWidget(self.password_label)
        self.password_container = QtWidgets.QFrame(self.login_frame)
        self.password_container.setStyleSheet("QFrame { border: none; background: transparent; }")
        self.password_container.setObjectName("password_container")
        self.password_layout = QtWidgets.QHBoxLayout(self.password_container)
        self.password_layout.setContentsMargins(0, 0, 0, 0)
        self.password_layout.setSpacing(0)
        self.password_layout.setObjectName("password_layout")
        self.password_input = QtWidgets.QLineEdit(self.password_container)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setStyleSheet("QLineEdit {\n"
"    padding: 15px;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 8px;\n"
"    font-size: 16px;\n"
"    background-color: white;\n"
"    min-height: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #2E86AB;\n"
"}\n"
"QLineEdit::placeholder {\n"
"    color: #999;\n"
"    font-style: italic;\n"
"}")
        self.password_input.setObjectName("password_input")
        self.password_layout.addWidget(self.password_input)
        self.show_password_btn = QtWidgets.QPushButton(self.password_container)
        self.show_password_btn.setMinimumSize(QtCore.QSize(45, 54))
        self.show_password_btn.setMaximumSize(QtCore.QSize(45, 54))
        self.show_password_btn.setStyleSheet("QPushButton {\n"
"    border: 2px solid #ddd;\n"
"    border-left: none;\n"
"    border-radius: 0px 8px 8px 0px;\n"
"    background-color: #f8f9fa;\n"
"    font-size: 14px;\n"
"    color: #666;\n"
"    margin-left: -2px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9ecef;\n"
"    color: #2E86AB;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #dee2e6;\n"
"}")
        self.show_password_btn.setObjectName("show_password_btn")
        self.password_layout.addWidget(self.show_password_btn)
        self.form_layout.addWidget(self.password_container)
        self.forgot_password_container = QtWidgets.QFrame(self.login_frame)
        self.forgot_password_container.setStyleSheet("QFrame { background: transparent; border: none; }")
        self.forgot_password_container.setObjectName("forgot_password_container")
        self.forgot_layout = QtWidgets.QHBoxLayout(self.forgot_password_container)
        self.forgot_layout.setContentsMargins(0, 15, 0, 15)
        self.forgot_layout.setObjectName("forgot_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.forgot_layout.addItem(spacerItem)
        self.forgot_password_label = QtWidgets.QLabel(self.forgot_password_container)
        self.forgot_password_label.setStyleSheet("QLabel {\n"
"    color: #2E86AB;\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"    text-decoration: underline;\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    min-height: 25px;\n"
"}\n"
"QLabel:hover {\n"
"    color: #1E5F7A;\n"
"    font-weight: bold;\n"
"}")
        self.forgot_password_label.setObjectName("forgot_password_label")
        self.forgot_layout.addWidget(self.forgot_password_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.forgot_layout.addItem(spacerItem1)
        self.form_layout.addWidget(self.forgot_password_container)
        self.login_button = QtWidgets.QPushButton(self.login_frame)
        self.login_button.setStyleSheet("QPushButton {\n"
"    padding: 18px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #2E86AB, stop:1 #A23B72);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    min-height: 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1E5F7A, stop:1 #7A2B52);\n"
"}\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1A4D63, stop:1 #5A1E3A);\n"
"}")
        self.login_button.setObjectName("login_button")
        self.form_layout.addWidget(self.login_button)
        self.error_label = QtWidgets.QLabel(self.login_frame)
        self.error_label.setStyleSheet("QLabel {\n"
"    color: #e74c3c;\n"
"    font-size: 14px;\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setWordWrap(True)
        self.error_label.setVisible(False)
        self.error_label.setObjectName("error_label")
        self.form_layout.addWidget(self.error_label)
        self.verticalLayout.addWidget(self.login_frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Hệ thống điều tra Windows - Đăng nhập"))
        self.title_label.setText(_translate("LoginWindow", "🔒 HỆ THỐNG ĐIỀU TRA MÁY TÍNH"))
        self.subtitle_label.setText(_translate("LoginWindow", "Nền tảng điều tra số"))
        self.username_label.setText(_translate("LoginWindow", "TÊN ĐĂNG NHẬP:"))
        self.username_input.setPlaceholderText(_translate("LoginWindow", "Nhập tên đăng nhập"))
        self.password_label.setText(_translate("LoginWindow", "MẬT KHẨU:"))
        self.password_input.setPlaceholderText(_translate("LoginWindow", "Nhập mật khẩu"))
        self.show_password_btn.setText(_translate("LoginWindow", "🔒"))
        self.forgot_password_label.setText(_translate("LoginWindow", "Quên mật khẩu?"))
        self.login_button.setText(_translate("LoginWindow", "ĐĂNG NHẬP"))