# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_user_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddUserDialog(object):
    def setupUi(self, AddUserDialog):
        AddUserDialog.setObjectName("AddUserDialog")
        AddUserDialog.resize(450, 400)
        AddUserDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddUserDialog)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usernameLabel = QtWidgets.QLabel(AddUserDialog)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout.addWidget(self.usernameLabel)
        self.usernameEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.usernameEdit.setObjectName("usernameEdit")
        self.verticalLayout.addWidget(self.usernameEdit)
        self.passwordLabel = QtWidgets.QLabel(AddUserDialog)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout.addWidget(self.passwordLabel)
        self.passwordEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.verticalLayout.addWidget(self.passwordEdit)
        self.fullNameLabel = QtWidgets.QLabel(AddUserDialog)
        self.fullNameLabel.setObjectName("fullNameLabel")
        self.verticalLayout.addWidget(self.fullNameLabel)
        self.fullNameEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.fullNameEdit.setObjectName("fullNameEdit")
        self.verticalLayout.addWidget(self.fullNameEdit)
        self.phoneLabel = QtWidgets.QLabel(AddUserDialog)
        self.phoneLabel.setObjectName("phoneLabel")
        self.verticalLayout.addWidget(self.phoneLabel)
        self.phoneEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.phoneEdit.setObjectName("phoneEdit")
        self.verticalLayout.addWidget(self.phoneEdit)
        self.emailLabel = QtWidgets.QLabel(AddUserDialog)
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout.addWidget(self.emailLabel)
        self.emailEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.emailEdit.setObjectName("emailEdit")
        self.verticalLayout.addWidget(self.emailEdit)
        self.roleLabel = QtWidgets.QLabel(AddUserDialog)
        self.roleLabel.setObjectName("roleLabel")
        self.verticalLayout.addWidget(self.roleLabel)
        self.roleCombo = QtWidgets.QComboBox(AddUserDialog)
        self.roleCombo.setObjectName("roleCombo")
        self.roleCombo.addItem("")
        self.roleCombo.addItem("")
        self.verticalLayout.addWidget(self.roleCombo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(10)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.saveBtn = QtWidgets.QPushButton(AddUserDialog)
        self.saveBtn.setMinimumSize(QtCore.QSize(100, 35))
        self.saveBtn.setObjectName("saveBtn")
        self.buttonLayout.addWidget(self.saveBtn)
        self.cancelBtn = QtWidgets.QPushButton(AddUserDialog)
        self.cancelBtn.setMinimumSize(QtCore.QSize(100, 35))
        self.cancelBtn.setObjectName("cancelBtn")
        self.buttonLayout.addWidget(self.cancelBtn)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(AddUserDialog)
        QtCore.QMetaObject.connectSlotsByName(AddUserDialog)

    def retranslateUi(self, AddUserDialog):
        _translate = QtCore.QCoreApplication.translate
        AddUserDialog.setWindowTitle(_translate("AddUserDialog", "Add/Edit User"))
        AddUserDialog.setStyleSheet(_translate("AddUserDialog", "QDialog {\n"
"    background-color: #f8f9fa;\n"
"    border-radius: 8px;\n"
"}\n"
"QLabel {\n"
"    color: #2c3e50;\n"
"    font-weight: bold;\n"
"    margin-bottom: 2px;\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    font-size: 12px;\n"
"    background-color: white;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #007bff;\n"
"    background-color: #f8f9ff;\n"
"}\n"
"QComboBox {\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-size: 12px;\n"
"    background-color: white;\n"
"}\n"
"QComboBox:focus {\n"
"    border-color: #007bff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/icons8-arrow-31-48.ico);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.9;\n"
"}\n"
"QPushButton:pressed {\n"
"    opacity: 0.8;\n"
"}"))
        self.usernameLabel.setText(_translate("AddUserDialog", "👤 Username:"))
        self.usernameEdit.setPlaceholderText(_translate("AddUserDialog", "Enter username..."))
        self.passwordLabel.setText(_translate("AddUserDialog", "🔒 Password:"))
        self.passwordEdit.setPlaceholderText(_translate("AddUserDialog", "Enter password..."))
        self.fullNameLabel.setText(_translate("AddUserDialog", "👨‍💼 Full Name:"))
        self.fullNameEdit.setPlaceholderText(_translate("AddUserDialog", "Enter full name..."))
        self.phoneLabel.setText(_translate("AddUserDialog", "📱 Phone:"))
        self.phoneEdit.setPlaceholderText(_translate("AddUserDialog", "Enter phone number..."))
        self.emailLabel.setText(_translate("AddUserDialog", "📧 Email:"))
        self.emailEdit.setPlaceholderText(_translate("AddUserDialog", "Enter email address..."))
        self.roleLabel.setText(_translate("AddUserDialog", "🎭 Role:"))
        self.roleCombo.setItemText(0, _translate("AddUserDialog", "ANALYST"))
        self.roleCombo.setItemText(1, _translate("AddUserDialog", "ADMIN"))
        self.saveBtn.setStyleSheet(_translate("AddUserDialog", "QPushButton {\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #218838;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e7e34;\n"
"}"))
        self.saveBtn.setText(_translate("AddUserDialog", "💾 Save"))
        self.cancelBtn.setStyleSheet(_translate("AddUserDialog", "QPushButton {\n"
"    background-color: #6c757d;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a6268;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #545b62;\n"
"}"))
        self.cancelBtn.setText(_translate("AddUserDialog", "❌ Cancel"))
