# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_confirm_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteConfirmDialog(object):
    def setupUi(self, DeleteConfirmDialog):
        DeleteConfirmDialog.setObjectName("DeleteConfirmDialog")
        DeleteConfirmDialog.resize(500, 450)
        DeleteConfirmDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DeleteConfirmDialog)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(DeleteConfirmDialog)
        self.headerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.infoFrame = QtWidgets.QFrame(DeleteConfirmDialog)
        self.infoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoFrame.setObjectName("infoFrame")
        self.infoLayout = QtWidgets.QVBoxLayout(self.infoFrame)
        self.infoLayout.setObjectName("infoLayout")
        self.infoLabel = QtWidgets.QLabel(self.infoFrame)
        self.infoLabel.setObjectName("infoLabel")
        self.infoLayout.addWidget(self.infoLabel)
        self.userInfoLabel = QtWidgets.QLabel(self.infoFrame)
        self.userInfoLabel.setObjectName("userInfoLabel")
        self.infoLayout.addWidget(self.userInfoLabel)
        self.verticalLayout.addWidget(self.infoFrame)
        self.warningFrame = QtWidgets.QFrame(DeleteConfirmDialog)
        self.warningFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.warningFrame.setObjectName("warningFrame")
        self.warningLayout = QtWidgets.QVBoxLayout(self.warningFrame)
        self.warningLayout.setObjectName("warningLayout")
        self.warningHeaderLabel = QtWidgets.QLabel(self.warningFrame)
        self.warningHeaderLabel.setObjectName("warningHeaderLabel")
        self.warningLayout.addWidget(self.warningHeaderLabel)
        self.warningContentLabel = QtWidgets.QLabel(self.warningFrame)
        self.warningContentLabel.setObjectName("warningContentLabel")
        self.warningLayout.addWidget(self.warningContentLabel)
        self.verticalLayout.addWidget(self.warningFrame)
        self.confirmLabel = QtWidgets.QLabel(DeleteConfirmDialog)
        self.confirmLabel.setObjectName("confirmLabel")
        self.verticalLayout.addWidget(self.confirmLabel)
        self.instructionLabel = QtWidgets.QLabel(DeleteConfirmDialog)
        self.instructionLabel.setObjectName("instructionLabel")
        self.verticalLayout.addWidget(self.instructionLabel)
        self.confirmInput = QtWidgets.QLineEdit(DeleteConfirmDialog)
        self.confirmInput.setObjectName("confirmInput")
        self.verticalLayout.addWidget(self.confirmInput)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(10)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.cancelBtn = QtWidgets.QPushButton(DeleteConfirmDialog)
        self.cancelBtn.setObjectName("cancelBtn")
        self.buttonLayout.addWidget(self.cancelBtn)
        self.deleteBtn = QtWidgets.QPushButton(DeleteConfirmDialog)
        self.deleteBtn.setEnabled(False)
        self.deleteBtn.setObjectName("deleteBtn")
        self.buttonLayout.addWidget(self.deleteBtn)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(DeleteConfirmDialog)
        QtCore.QMetaObject.connectSlotsByName(DeleteConfirmDialog)

    def retranslateUi(self, DeleteConfirmDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteConfirmDialog.setWindowTitle(_translate("DeleteConfirmDialog", "Confirm Permanent Deletion"))
        DeleteConfirmDialog.setStyleSheet(_translate("DeleteConfirmDialog", "QDialog {\n"
"    background-color: #f8f9fa;\n"
"    border-radius: 8px;\n"
"}\n"
"QLabel {\n"
"    color: #2c3e50;\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid #dc3545;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    font-size: 12px;\n"
"    background-color: white;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #a71e2a;\n"
"    background-color: #fff5f5;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    min-width: 100px;\n"
"    min-height: 35px;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 0.9;\n"
"}\n"
"QPushButton:pressed {\n"
"    opacity: 0.8;\n"
"}"))
        self.headerLabel.setText(_translate("DeleteConfirmDialog", "💀 CONFIRM PERMANENT DELETION"))
        self.headerLabel.setStyleSheet(_translate("DeleteConfirmDialog", "QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #dc3545;\n"
"    margin: 10px;\n"
"}"))
        self.infoFrame.setStyleSheet(_translate("DeleteConfirmDialog", "QFrame {\n"
"    background-color: #f8d7da;\n"
"    border: 2px solid #dc3545;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}"))
        self.infoLabel.setText(_translate("DeleteConfirmDialog", "📋 User Information to be PERMANENTLY DELETED:"))
        self.infoLabel.setStyleSheet(_translate("DeleteConfirmDialog", "QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"    line-height: 1.4;\n"
"}"))
        self.userInfoLabel.setText(_translate("DeleteConfirmDialog", "👤 Username: [username]\n"
"👨‍💼 Full Name: [full_name]\n"
"🎭 Role: [role]\n"
"📧 Email: [email]"))
        self.userInfoLabel.setStyleSheet(_translate("DeleteConfirmDialog", "QLabel {\n"
"    padding: 5px;\n"
"    background-color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 4px;\n"
"}"))
        self.warningFrame.setStyleSheet(_translate("DeleteConfirmDialog", "QFrame {\n"
"    background-color: #fff3cd;\n"
"    border: 2px solid #ffc107;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}"))
        self.warningHeaderLabel.setText(_translate("DeleteConfirmDialog", "🚨 SERIOUS WARNING:"))
        self.warningHeaderLabel.setStyleSheet(_translate("DeleteConfirmDialog", "QLabel {\n"
"    font-weight: bold;\n"
"    color: #856404;\n"
"}"))
        self.warningContentLabel.setText(_translate("DeleteConfirmDialog", "💀 WHAT WILL BE LOST PERMANENTLY:\n"
"• All user information\n"
"• All related data\n"
"\n"
"⚠️ THIS ACTION CANNOT BE UNDONE!\n"
"\n"
"💡 SUGGESTION: If you only want to prevent login,\n"
"   use the \"🔄 Toggle Status\" button instead."))
        self.warningContentLabel.setStyleSheet(_translate("DeleteConfirmDialog", "QLabel {\n"
"    font-size: 11px;\n"
"    line-height: 1.4;\n"
"    color: #856404;\n"
"}"))
        self.confirmLabel.setText(_translate("DeleteConfirmDialog", "🔐 CONFIRM PERMANENT DELETION:"))
        self.confirmLabel.setStyleSheet(_translate("DeleteConfirmDialog", "QLabel {\n"
"    font-weight: bold;\n"
"    margin: 10px 0 5px 0;\n"
"}"))
        self.instructionLabel.setText(_translate("DeleteConfirmDialog", "Type \'[username]\' to confirm:"))
        self.instructionLabel.setStyleSheet(_translate("DeleteConfirmDialog", "QLabel {\n"
"    margin: 0 0 5px 0;\n"
"}"))
        self.confirmInput.setPlaceholderText(_translate("DeleteConfirmDialog", "Type username here to confirm..."))
        self.cancelBtn.setStyleSheet(_translate("DeleteConfirmDialog", "QPushButton {\n"
"    background-color: #6c757d;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a6268;\n"
"}"))
        self.cancelBtn.setText(_translate("DeleteConfirmDialog", "❌ Cancel"))
        self.deleteBtn.setStyleSheet(_translate("DeleteConfirmDialog", "QPushButton {\n"
"    background-color: #dc3545;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover:enabled {\n"
"    background-color: #c82333;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #6c757d;\n"
"    color: #adb5bd;\n"
"}"))
        self.deleteBtn.setText(_translate("DeleteConfirmDialog", "💀 DELETE PERMANENTLY"))
