# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EvidenceAnalysisWidget(object):
    def setupUi(self, EvidenceAnalysisWidget):
        EvidenceAnalysisWidget.setObjectName("EvidenceAnalysisWidget")
        EvidenceAnalysisWidget.resize(1400, 900)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(EvidenceAnalysisWidget)
        self.verticalLayout_main.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_main.setSpacing(0)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.caseTitleBar = QtWidgets.QFrame(EvidenceAnalysisWidget)
        self.caseTitleBar.setMinimumSize(QtCore.QSize(0, 40))
        self.caseTitleBar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.caseTitleBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.caseTitleBar.setObjectName("caseTitleBar")
        self.horizontalLayout_title = QtWidgets.QHBoxLayout(self.caseTitleBar)
        self.horizontalLayout_title.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout_title.setObjectName("horizontalLayout_title")
        self.labelEvidence = QtWidgets.QLabel(self.caseTitleBar)
        self.labelEvidence.setStyleSheet("QLabel {\n"
"    color: black;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    margin-right: 5px;\n"
"}")
        self.labelEvidence.setObjectName("labelEvidence")
        self.horizontalLayout_title.addWidget(self.labelEvidence)
        self.cmbEvidenceArtifacts = QtWidgets.QComboBox(self.caseTitleBar)
        self.cmbEvidenceArtifacts.setMinimumSize(QtCore.QSize(200, 28))
        self.cmbEvidenceArtifacts.setMaximumSize(QtCore.QSize(300, 28))
        self.cmbEvidenceArtifacts.setStyleSheet("QComboBox {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"    padding: 5px 10px;\n"
"    background-color: white;\n"
"    color: black;\n"
"    font-size: 12px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid black;\n"
"    margin-right: 5px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"    selection-background-color: #e6f3ff;\n"
"}")
        self.cmbEvidenceArtifacts.setObjectName("cmbEvidenceArtifacts")
        self.horizontalLayout_title.addWidget(self.cmbEvidenceArtifacts)
        self.btnLoadSelectedEvidence = QtWidgets.QToolButton(self.caseTitleBar)
        self.btnLoadSelectedEvidence.setMinimumSize(QtCore.QSize(80, 28))
        self.btnLoadSelectedEvidence.setMaximumSize(QtCore.QSize(80, 28))
        self.btnLoadSelectedEvidence.setStyleSheet("QToolButton {\n"
"    border: 1px solid #007bff;\n"
"    border-radius: 4px;\n"
"    padding: 5px 10px;\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: #004085;\n"
"}\n"
"QToolButton:disabled {\n"
"    background-color: #ccc;\n"
"    border-color: #ccc;\n"
"    color: #666;\n"
"}")
        self.btnLoadSelectedEvidence.setObjectName("btnLoadSelectedEvidence")
        self.horizontalLayout_title.addWidget(self.btnLoadSelectedEvidence)
        self.btnRefreshEvidence = QtWidgets.QToolButton(self.caseTitleBar)
        self.btnRefreshEvidence.setMinimumSize(QtCore.QSize(30, 28))
        self.btnRefreshEvidence.setMaximumSize(QtCore.QSize(30, 28))
        self.btnRefreshEvidence.setStyleSheet("QToolButton {\n"
"    border: 1px solid #6c757d;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    background-color: #6c757d;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: #5a6268;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: #4e555b;\n"
"}")
        self.btnRefreshEvidence.setObjectName("btnRefreshEvidence")
        self.horizontalLayout_title.addWidget(self.btnRefreshEvidence)
        self.line = QtWidgets.QFrame(self.caseTitleBar)
        self.line.setMinimumSize(QtCore.QSize(1, 25))
        self.line.setMaximumSize(QtCore.QSize(1, 25))
        self.line.setStyleSheet("Line {\n"
"    background-color: #34495e;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_title.addWidget(self.line)
        self.labelCaseInfo = QtWidgets.QLabel(self.caseTitleBar)
        self.labelCaseInfo.setStyleSheet("QLabel {\n"
"    color: black;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    margin-left: 10px;\n"
"}")
        self.labelCaseInfo.setObjectName("labelCaseInfo")
        self.horizontalLayout_title.addWidget(self.labelCaseInfo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_title.addItem(spacerItem)
        self.verticalLayout_main.addWidget(self.caseTitleBar)
        self.mainSplitter = QtWidgets.QSplitter(EvidenceAnalysisWidget)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setObjectName("mainSplitter")
        self.investigationFrame = QtWidgets.QFrame(self.mainSplitter)
        self.investigationFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.investigationFrame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.investigationFrame.setStyleSheet("QFrame {\n"
"    background-color: #f5f5f5;\n"
"    border-right: 1px solid #ddd;\n"
"}")
        self.investigationFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.investigationFrame.setObjectName("investigationFrame")
        self.verticalLayout_left = QtWidgets.QVBoxLayout(self.investigationFrame)
        self.verticalLayout_left.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_left.setSpacing(0)
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.treeInvestigation = QtWidgets.QTreeWidget(self.investigationFrame)
        self.treeInvestigation.setStyleSheet("QTreeWidget {\n"
"    border: none;\n"
"    background-color: #f5f5f5;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTreeWidget::item {\n"
"    padding: 5px;\n"
"    border-bottom: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"QTreeWidget::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeWidget::item:hover {\n"
"    background-color: #ecf0f1;\n"
"}\n"
"\n"
"QTreeWidget::branch {\n"
"    background-color: #f5f5f5;\n"
"}")
        self.treeInvestigation.setHeaderHidden(True)
        self.treeInvestigation.setObjectName("treeInvestigation")
        self.verticalLayout_left.addWidget(self.treeInvestigation)
        self.rightSplitter = QtWidgets.QSplitter(self.mainSplitter)
        self.rightSplitter.setOrientation(QtCore.Qt.Vertical)
        self.rightSplitter.setObjectName("rightSplitter")
        self.tabWorkArea = QtWidgets.QTabWidget(self.rightSplitter)
        self.tabWorkArea.setMinimumSize(QtCore.QSize(0, 400))
        self.tabWorkArea.setStyleSheet("QTabWidget::pane {\n"
"    border: 1px solid #ddd;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #ecf0f1;\n"
"    padding: 8px 15px;\n"
"    margin-right: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: white;\n"
"    border-bottom: 2px solid #3498db;\n"
"}")
        self.tabWorkArea.setObjectName("tabWorkArea")
        self.tabFileBrowser = QtWidgets.QWidget()
        self.tabFileBrowser.setObjectName("tabFileBrowser")
        self.verticalLayout_browser = QtWidgets.QVBoxLayout(self.tabFileBrowser)
        self.verticalLayout_browser.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_browser.setObjectName("verticalLayout_browser")
        self.tableFiles = QtWidgets.QTableWidget(self.tabFileBrowser)
        self.tableFiles.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableFiles.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    gridline-color: #e0e0e0;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #ecf0f1;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    border-right: 1px solid #ddd;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"    color: #000;\n"
"}")
        self.tableFiles.setAlternatingRowColors(True)
        self.tableFiles.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableFiles.setObjectName("tableFiles")
        self.tableFiles.setColumnCount(8)
        self.tableFiles.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiles.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiles.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiles.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiles.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiles.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiles.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiles.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiles.setHorizontalHeaderItem(7, item)
        self.tableFiles.horizontalHeader().setDefaultSectionSize(120)
        self.tableFiles.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_browser.addWidget(self.tableFiles)
        self.tabWorkArea.addTab(self.tabFileBrowser, "")
        self.tabTimeline = QtWidgets.QWidget()
        self.tabTimeline.setObjectName("tabTimeline")
        self.verticalLayout_timeline = QtWidgets.QVBoxLayout(self.tabTimeline)
        self.verticalLayout_timeline.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_timeline.setObjectName("verticalLayout_timeline")
        self.tableTimeline = QtWidgets.QTableWidget(self.tabTimeline)
        self.tableTimeline.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    gridline-color: #e0e0e0;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #ecf0f1;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    border-right: 1px solid #ddd;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"    color: #000;\n"
"}")
        self.tableTimeline.setAlternatingRowColors(True)
        self.tableTimeline.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableTimeline.setObjectName("tableTimeline")
        self.tableTimeline.setColumnCount(5)
        self.tableTimeline.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTimeline.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTimeline.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTimeline.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTimeline.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTimeline.setHorizontalHeaderItem(4, item)
        self.verticalLayout_timeline.addWidget(self.tableTimeline)
        self.tabWorkArea.addTab(self.tabTimeline, "")
        self.tabSearch = QtWidgets.QWidget()
        self.tabSearch.setObjectName("tabSearch")
        self.verticalLayout_search = QtWidgets.QVBoxLayout(self.tabSearch)
        self.verticalLayout_search.setObjectName("verticalLayout_search")
        self.searchControlFrame = QtWidgets.QFrame(self.tabSearch)
        self.searchControlFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.searchControlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchControlFrame.setObjectName("searchControlFrame")
        self.horizontalLayout_search = QtWidgets.QHBoxLayout(self.searchControlFrame)
        self.horizontalLayout_search.setObjectName("horizontalLayout_search")
        self.labelSearch = QtWidgets.QLabel(self.searchControlFrame)
        self.labelSearch.setObjectName("labelSearch")
        self.horizontalLayout_search.addWidget(self.labelSearch)
        self.lineEditSearch = QtWidgets.QLineEdit(self.searchControlFrame)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.horizontalLayout_search.addWidget(self.lineEditSearch)
        self.btnSearch = QtWidgets.QPushButton(self.searchControlFrame)
        self.btnSearch.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}")
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout_search.addWidget(self.btnSearch)
        self.verticalLayout_search.addWidget(self.searchControlFrame)
        self.tableSearchResults = QtWidgets.QTableWidget(self.tabSearch)
        self.tableSearchResults.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableSearchResults.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    gridline-color: #e0e0e0;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #ecf0f1;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    border-right: 1px solid #ddd;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"    color: #000;\n"
"}")
        self.tableSearchResults.setAlternatingRowColors(True)
        self.tableSearchResults.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableSearchResults.setObjectName("tableSearchResults")
        self.tableSearchResults.setColumnCount(4)
        self.tableSearchResults.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSearchResults.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSearchResults.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSearchResults.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSearchResults.setHorizontalHeaderItem(3, item)
        self.verticalLayout_search.addWidget(self.tableSearchResults)
        self.tabWorkArea.addTab(self.tabSearch, "")
        self.tabDetails = QtWidgets.QTabWidget(self.rightSplitter)
        self.tabDetails.setMinimumSize(QtCore.QSize(0, 200))
        self.tabDetails.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tabDetails.setStyleSheet("QTabWidget::pane {\n"
"    border: 1px solid #ddd;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #ecf0f1;\n"
"    padding: 6px 12px;\n"
"    margin-right: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: white;\n"
"    border-bottom: 2px solid #3498db;\n"
"}")
        self.tabDetails.setObjectName("tabDetails")
        self.tabContent = QtWidgets.QWidget()
        self.tabContent.setObjectName("tabContent")
        self.verticalLayout_content = QtWidgets.QVBoxLayout(self.tabContent)
        self.verticalLayout_content.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_content.setObjectName("verticalLayout_content")
        self.tabContentView = QtWidgets.QTabWidget(self.tabContent)
        self.tabContentView.setStyleSheet("QTabBar::tab {\n"
"    padding: 4px 10px;\n"
"    font-size: 11px;\n"
"}")
        self.tabContentView.setObjectName("tabContentView")
        self.tabHex = QtWidgets.QWidget()
        self.tabHex.setObjectName("tabHex")
        self.verticalLayout_hex = QtWidgets.QVBoxLayout(self.tabHex)
        self.verticalLayout_hex.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_hex.setObjectName("verticalLayout_hex")
        self.textHexView = QtWidgets.QTextEdit(self.tabHex)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.textHexView.setFont(font)
        self.textHexView.setReadOnly(True)
        self.textHexView.setObjectName("textHexView")
        self.verticalLayout_hex.addWidget(self.textHexView)
        self.tabContentView.addTab(self.tabHex, "")
        self.tabText = QtWidgets.QWidget()
        self.tabText.setObjectName("tabText")
        self.verticalLayout_text = QtWidgets.QVBoxLayout(self.tabText)
        self.verticalLayout_text.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_text.setObjectName("verticalLayout_text")
        self.textContentView = QtWidgets.QTextEdit(self.tabText)
        self.textContentView.setReadOnly(True)
        self.textContentView.setObjectName("textContentView")
        self.verticalLayout_text.addWidget(self.textContentView)
        self.tabContentView.addTab(self.tabText, "")
        self.tabPicture = QtWidgets.QWidget()
        self.tabPicture.setObjectName("tabPicture")
        self.verticalLayout_picture = QtWidgets.QVBoxLayout(self.tabPicture)
        self.verticalLayout_picture.setObjectName("verticalLayout_picture")
        self.labelPicture = QtWidgets.QLabel(self.tabPicture)
        self.labelPicture.setStyleSheet("QLabel {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #ddd;\n"
"}")
        self.labelPicture.setText("")
        self.labelPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPicture.setObjectName("labelPicture")
        self.verticalLayout_picture.addWidget(self.labelPicture)
        self.tabContentView.addTab(self.tabPicture, "")
        self.verticalLayout_content.addWidget(self.tabContentView)
        self.tabDetails.addTab(self.tabContent, "")
        self.tabMetadata = QtWidgets.QWidget()
        self.tabMetadata.setObjectName("tabMetadata")
        self.verticalLayout_metadata = QtWidgets.QVBoxLayout(self.tabMetadata)
        self.verticalLayout_metadata.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_metadata.setObjectName("verticalLayout_metadata")
        self.tableMetadata = QtWidgets.QTableWidget(self.tabMetadata)
        self.tableMetadata.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    gridline-color: #e0e0e0;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #ecf0f1;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    border-right: 1px solid #ddd;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"    color: #000;\n"
"}")
        self.tableMetadata.setAlternatingRowColors(True)
        self.tableMetadata.setObjectName("tableMetadata")
        self.tableMetadata.setColumnCount(2)
        self.tableMetadata.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableMetadata.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMetadata.setHorizontalHeaderItem(1, item)
        self.verticalLayout_metadata.addWidget(self.tableMetadata)
        self.tabDetails.addTab(self.tabMetadata, "")
        self.tabFileProperties = QtWidgets.QWidget()
        self.tabFileProperties.setObjectName("tabFileProperties")
        self.verticalLayout_properties = QtWidgets.QVBoxLayout(self.tabFileProperties)
        self.verticalLayout_properties.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_properties.setObjectName("verticalLayout_properties")
        self.tableProperties = QtWidgets.QTableWidget(self.tabFileProperties)
        self.tableProperties.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    gridline-color: #e0e0e0;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #ecf0f1;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    border-right: 1px solid #ddd;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"    color: #000;\n"
"}")
        self.tableProperties.setAlternatingRowColors(True)
        self.tableProperties.setObjectName("tableProperties")
        self.tableProperties.setColumnCount(2)
        self.tableProperties.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProperties.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProperties.setHorizontalHeaderItem(1, item)
        self.verticalLayout_properties.addWidget(self.tableProperties)
        self.tabDetails.addTab(self.tabFileProperties, "")
        self.tabAnalysisResults = QtWidgets.QWidget()
        self.tabAnalysisResults.setObjectName("tabAnalysisResults")
        self.verticalLayout_analysis = QtWidgets.QVBoxLayout(self.tabAnalysisResults)
        self.verticalLayout_analysis.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_analysis.setObjectName("verticalLayout_analysis")
        self.textAnalysisResults = QtWidgets.QTextEdit(self.tabAnalysisResults)
        self.textAnalysisResults.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"    background-color: #f9f9f9;\n"
"    font-size: 12px;\n"
"}")
        self.textAnalysisResults.setReadOnly(True)
        self.textAnalysisResults.setObjectName("textAnalysisResults")
        self.verticalLayout_analysis.addWidget(self.textAnalysisResults)
        self.tabDetails.addTab(self.tabAnalysisResults, "")
        self.verticalLayout_main.addWidget(self.mainSplitter)

        self.retranslateUi(EvidenceAnalysisWidget)
        self.tabWorkArea.setCurrentIndex(0)
        self.tabDetails.setCurrentIndex(0)
        self.tabContentView.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EvidenceAnalysisWidget)

    def retranslateUi(self, EvidenceAnalysisWidget):
        _translate = QtCore.QCoreApplication.translate
        EvidenceAnalysisWidget.setWindowTitle(_translate("EvidenceAnalysisWidget", "Evidence Analysis"))
        self.labelEvidence.setText(_translate("EvidenceAnalysisWidget", "Evidence:"))
        self.cmbEvidenceArtifacts.setToolTip(_translate("EvidenceAnalysisWidget", "Chọn evidence artifact để phân tích"))
        self.btnLoadSelectedEvidence.setToolTip(_translate("EvidenceAnalysisWidget", "Load evidence được chọn"))
        self.btnLoadSelectedEvidence.setText(_translate("EvidenceAnalysisWidget", "Load"))
        self.btnRefreshEvidence.setToolTip(_translate("EvidenceAnalysisWidget", "Refresh danh sách evidence"))
        self.btnRefreshEvidence.setText(_translate("EvidenceAnalysisWidget", "🔄"))
        self.labelCaseInfo.setText(_translate("EvidenceAnalysisWidget", "File Analysis - No evidence loaded"))
        self.treeInvestigation.headerItem().setText(0, _translate("EvidenceAnalysisWidget", "Data Sources"))
        self.tableFiles.setSortingEnabled(False)
        item = self.tableFiles.horizontalHeaderItem(0)
        item.setText(_translate("EvidenceAnalysisWidget", "Name"))
        item = self.tableFiles.horizontalHeaderItem(1)
        item.setText(_translate("EvidenceAnalysisWidget", "Size"))
        item = self.tableFiles.horizontalHeaderItem(2)
        item.setText(_translate("EvidenceAnalysisWidget", "Modified"))
        item = self.tableFiles.horizontalHeaderItem(3)
        item.setText(_translate("EvidenceAnalysisWidget", "Accessed"))
        item = self.tableFiles.horizontalHeaderItem(4)
        item.setText(_translate("EvidenceAnalysisWidget", "Created"))
        item = self.tableFiles.horizontalHeaderItem(5)
        item.setText(_translate("EvidenceAnalysisWidget", "MFT Modified"))
        item = self.tableFiles.horizontalHeaderItem(6)
        item.setText(_translate("EvidenceAnalysisWidget", "Type"))
        item = self.tableFiles.horizontalHeaderItem(7)
        item.setText(_translate("EvidenceAnalysisWidget", "Path"))
        self.tabWorkArea.setTabText(self.tabWorkArea.indexOf(self.tabFileBrowser), _translate("EvidenceAnalysisWidget", "File Browser"))
        self.tableTimeline.setSortingEnabled(False)
        item = self.tableTimeline.horizontalHeaderItem(0)
        item.setText(_translate("EvidenceAnalysisWidget", "Date/Time"))
        item = self.tableTimeline.horizontalHeaderItem(1)
        item.setText(_translate("EvidenceAnalysisWidget", "Source"))
        item = self.tableTimeline.horizontalHeaderItem(2)
        item.setText(_translate("EvidenceAnalysisWidget", "Type"))
        item = self.tableTimeline.horizontalHeaderItem(3)
        item.setText(_translate("EvidenceAnalysisWidget", "Description"))
        item = self.tableTimeline.horizontalHeaderItem(4)
        item.setText(_translate("EvidenceAnalysisWidget", "File/Artifact"))
        self.tabWorkArea.setTabText(self.tabWorkArea.indexOf(self.tabTimeline), _translate("EvidenceAnalysisWidget", "Timeline"))
        self.labelSearch.setText(_translate("EvidenceAnalysisWidget", "Keywords:"))
        self.lineEditSearch.setPlaceholderText(_translate("EvidenceAnalysisWidget", "Enter search keywords..."))
        self.btnSearch.setText(_translate("EvidenceAnalysisWidget", "Search"))
        self.tableSearchResults.setSortingEnabled(False)
        item = self.tableSearchResults.horizontalHeaderItem(0)
        item.setText(_translate("EvidenceAnalysisWidget", "File Name"))
        item = self.tableSearchResults.horizontalHeaderItem(1)
        item.setText(_translate("EvidenceAnalysisWidget", "Path"))
        item = self.tableSearchResults.horizontalHeaderItem(2)
        item.setText(_translate("EvidenceAnalysisWidget", "Hits"))
        item = self.tableSearchResults.horizontalHeaderItem(3)
        item.setText(_translate("EvidenceAnalysisWidget", "Modified"))
        self.tabWorkArea.setTabText(self.tabWorkArea.indexOf(self.tabSearch), _translate("EvidenceAnalysisWidget", "Search"))
        self.tabContentView.setTabText(self.tabContentView.indexOf(self.tabHex), _translate("EvidenceAnalysisWidget", "Hex"))
        self.tabContentView.setTabText(self.tabContentView.indexOf(self.tabText), _translate("EvidenceAnalysisWidget", "Text"))
        self.tabContentView.setTabText(self.tabContentView.indexOf(self.tabPicture), _translate("EvidenceAnalysisWidget", "Picture"))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabContent), _translate("EvidenceAnalysisWidget", "Content"))
        item = self.tableMetadata.horizontalHeaderItem(0)
        item.setText(_translate("EvidenceAnalysisWidget", "Property"))
        item = self.tableMetadata.horizontalHeaderItem(1)
        item.setText(_translate("EvidenceAnalysisWidget", "Value"))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabMetadata), _translate("EvidenceAnalysisWidget", "Metadata"))
        item = self.tableProperties.horizontalHeaderItem(0)
        item.setText(_translate("EvidenceAnalysisWidget", "Property"))
        item = self.tableProperties.horizontalHeaderItem(1)
        item.setText(_translate("EvidenceAnalysisWidget", "Value"))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabFileProperties), _translate("EvidenceAnalysisWidget", "File Properties"))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabAnalysisResults), _translate("EvidenceAnalysisWidget", "Analysis Results"))
