# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registry_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistryAnalysisWidget(object):
    def setupUi(self, RegistryAnalysisWidget):
        RegistryAnalysisWidget.setObjectName("RegistryAnalysisWidget")
        RegistryAnalysisWidget.resize(1200, 800)
        self.mainLayout = QtWidgets.QVBoxLayout(RegistryAnalysisWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.toolbarFrame = QtWidgets.QFrame(RegistryAnalysisWidget)
        self.toolbarFrame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.toolbarFrame.setStyleSheet("QFrame#toolbarFrame {\n"
"    background-color: #f8f9fa;\n"
"    border-bottom: 1px solid #dee2e6;\n"
"}")
        self.toolbarFrame.setObjectName("toolbarFrame")
        self.toolbarLayout = QtWidgets.QHBoxLayout(self.toolbarFrame)
        self.toolbarLayout.setContentsMargins(8, 8, 8, 8)
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.caseInfoLabel = QtWidgets.QLabel(self.toolbarFrame)
        self.caseInfoLabel.setStyleSheet("font-weight: bold; color: #495057;")
        self.caseInfoLabel.setObjectName("caseInfoLabel")
        self.toolbarLayout.addWidget(self.caseInfoLabel)
        self.line1 = QtWidgets.QFrame(self.toolbarFrame)
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.toolbarLayout.addWidget(self.line1)
        self.cmbHiveArtifacts = QtWidgets.QComboBox(self.toolbarFrame)
        self.cmbHiveArtifacts.setMinimumSize(QtCore.QSize(250, 30))
        self.cmbHiveArtifacts.setStyleSheet("QComboBox {\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color: #80bdff;\n"
"}")
        self.cmbHiveArtifacts.setObjectName("cmbHiveArtifacts")
        self.toolbarLayout.addWidget(self.cmbHiveArtifacts)
        self.btnLoadSelectedHive = QtWidgets.QPushButton(self.toolbarFrame)
        self.btnLoadSelectedHive.setStyleSheet("QPushButton {\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #6c757d;\n"
"}")
        self.btnLoadSelectedHive.setObjectName("btnLoadSelectedHive")
        self.toolbarLayout.addWidget(self.btnLoadSelectedHive)
        self.btnRefreshHives = QtWidgets.QPushButton(self.toolbarFrame)
        self.btnRefreshHives.setMaximumSize(QtCore.QSize(30, 30))
        self.btnRefreshHives.setObjectName("btnRefreshHives")
        self.toolbarLayout.addWidget(self.btnRefreshHives)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolbarLayout.addItem(spacerItem)
        self.statusIndicator = QtWidgets.QLabel(self.toolbarFrame)
        self.statusIndicator.setStyleSheet("color: #28a745; font-weight: bold;")
        self.statusIndicator.setObjectName("statusIndicator")
        self.toolbarLayout.addWidget(self.statusIndicator)
        self.btnExport = QtWidgets.QPushButton(self.toolbarFrame)
        self.btnExport.setStyleSheet("QPushButton {\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #218838;\n"
"}")
        self.btnExport.setObjectName("btnExport")
        self.toolbarLayout.addWidget(self.btnExport)
        self.mainLayout.addWidget(self.toolbarFrame)
        self.mainSplitter = QtWidgets.QSplitter(RegistryAnalysisWidget)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setObjectName("mainSplitter")
        self.leftPanel = QtWidgets.QFrame(self.mainSplitter)
        self.leftPanel.setMinimumSize(QtCore.QSize(300, 0))
        self.leftPanel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.leftPanel.setObjectName("leftPanel")
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.leftLayout.setContentsMargins(0, 0, 0, 0)
        self.leftLayout.setObjectName("leftLayout")
        self.treeToolbar = QtWidgets.QFrame(self.leftPanel)
        self.treeToolbar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.treeToolbar.setStyleSheet("background-color: #f8f9fa;")
        self.treeToolbar.setObjectName("treeToolbar")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.treeToolbar)
        self.hboxlayout.setContentsMargins(5, 5, 5, 5)
        self.hboxlayout.setObjectName("hboxlayout")
        self.btnExpandAll = QtWidgets.QPushButton(self.treeToolbar)
        self.btnExpandAll.setMaximumSize(QtCore.QSize(25, 25))
        self.btnExpandAll.setObjectName("btnExpandAll")
        self.hboxlayout.addWidget(self.btnExpandAll)
        self.btnCollapseAll = QtWidgets.QPushButton(self.treeToolbar)
        self.btnCollapseAll.setMaximumSize(QtCore.QSize(25, 25))
        self.btnCollapseAll.setObjectName("btnCollapseAll")
        self.hboxlayout.addWidget(self.btnCollapseAll)
        self.txtTreeFilter = QtWidgets.QLineEdit(self.treeToolbar)
        self.txtTreeFilter.setClearButtonEnabled(True)
        self.txtTreeFilter.setObjectName("txtTreeFilter")
        self.hboxlayout.addWidget(self.txtTreeFilter)
        self.leftLayout.addWidget(self.treeToolbar)
        self.registryTree = QtWidgets.QTreeView(self.leftPanel)
        self.registryTree.setAlternatingRowColors(True)
        self.registryTree.setAnimated(True)
        self.registryTree.setObjectName("registryTree")
        self.leftLayout.addWidget(self.registryTree)
        self.centerPanel = QtWidgets.QFrame(self.mainSplitter)
        self.centerPanel.setObjectName("centerPanel")
        self.centerLayout = QtWidgets.QVBoxLayout(self.centerPanel)
        self.centerLayout.setContentsMargins(0, 0, 0, 0)
        self.centerLayout.setObjectName("centerLayout")
        self.pathBar = QtWidgets.QFrame(self.centerPanel)
        self.pathBar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.pathBar.setStyleSheet("background-color: #f8f9fa; border-bottom: 1px solid #dee2e6;")
        self.pathBar.setObjectName("pathBar")
        self.hboxlayout1 = QtWidgets.QHBoxLayout(self.pathBar)
        self.hboxlayout1.setContentsMargins(8, 8, 8, 8)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.lblPath = QtWidgets.QLabel(self.pathBar)
        self.lblPath.setStyleSheet("font-weight: bold;")
        self.lblPath.setObjectName("lblPath")
        self.hboxlayout1.addWidget(self.lblPath)
        self.txtCurrentPath = QtWidgets.QLineEdit(self.pathBar)
        self.txtCurrentPath.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    background-color: white;\n"
"}")
        self.txtCurrentPath.setReadOnly(True)
        self.txtCurrentPath.setObjectName("txtCurrentPath")
        self.hboxlayout1.addWidget(self.txtCurrentPath)
        self.btnCopyPath = QtWidgets.QPushButton(self.pathBar)
        self.btnCopyPath.setMaximumSize(QtCore.QSize(30, 25))
        self.btnCopyPath.setObjectName("btnCopyPath")
        self.hboxlayout1.addWidget(self.btnCopyPath)
        self.centerLayout.addWidget(self.pathBar)
        self.verticalSplitter = QtWidgets.QSplitter(self.centerPanel)
        self.verticalSplitter.setOrientation(QtCore.Qt.Vertical)
        self.verticalSplitter.setObjectName("verticalSplitter")
        self.valuesTable = QtWidgets.QTableView(self.verticalSplitter)
        self.valuesTable.setAlternatingRowColors(True)
        self.valuesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.valuesTable.setSortingEnabled(True)
        self.valuesTable.setObjectName("valuesTable")
        self.valuesTable.horizontalHeader().setStretchLastSection(True)
        self.detailTabs = QtWidgets.QTabWidget(self.verticalSplitter)
        self.detailTabs.setMaximumSize(QtCore.QSize(16777215, 300))
        self.detailTabs.setObjectName("detailTabs")
        self.tabHex = QtWidgets.QWidget()
        self.tabHex.setObjectName("tabHex")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.tabHex)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hexView = QtWidgets.QTextEdit(self.tabHex)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.hexView.setFont(font)
        self.hexView.setReadOnly(True)
        self.hexView.setObjectName("hexView")
        self.vboxlayout.addWidget(self.hexView)
        self.detailTabs.addTab(self.tabHex, "")
        self.tabDecoded = QtWidgets.QWidget()
        self.tabDecoded.setObjectName("tabDecoded")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.tabDecoded)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.formatFrame = QtWidgets.QFrame(self.tabDecoded)
        self.formatFrame.setMaximumSize(QtCore.QSize(16777215, 35))
        self.formatFrame.setObjectName("formatFrame")
        self.hboxlayout2 = QtWidgets.QHBoxLayout(self.formatFrame)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.lblFormat = QtWidgets.QLabel(self.formatFrame)
        self.lblFormat.setObjectName("lblFormat")
        self.hboxlayout2.addWidget(self.lblFormat)
        self.cmbFormat = QtWidgets.QComboBox(self.formatFrame)
        self.cmbFormat.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbFormat.setObjectName("cmbFormat")
        self.cmbFormat.addItem("")
        self.cmbFormat.addItem("")
        self.cmbFormat.addItem("")
        self.cmbFormat.addItem("")
        self.cmbFormat.addItem("")
        self.cmbFormat.addItem("")
        self.cmbFormat.addItem("")
        self.hboxlayout2.addWidget(self.cmbFormat)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem1)
        self.vboxlayout1.addWidget(self.formatFrame)
        self.decodedView = QtWidgets.QTextEdit(self.tabDecoded)
        self.decodedView.setReadOnly(True)
        self.decodedView.setObjectName("decodedView")
        self.vboxlayout1.addWidget(self.decodedView)
        self.detailTabs.addTab(self.tabDecoded, "")
        self.tabAnalysis = QtWidgets.QWidget()
        self.tabAnalysis.setObjectName("tabAnalysis")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.tabAnalysis)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.analysisView = QtWidgets.QTextEdit(self.tabAnalysis)
        self.analysisView.setReadOnly(True)
        self.analysisView.setObjectName("analysisView")
        self.vboxlayout2.addWidget(self.analysisView)
        self.detailTabs.addTab(self.tabAnalysis, "")
        self.tabTimeline = QtWidgets.QWidget()
        self.tabTimeline.setObjectName("tabTimeline")
        self.vboxlayout3 = QtWidgets.QVBoxLayout(self.tabTimeline)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.timelineTable = QtWidgets.QTableWidget(self.tabTimeline)
        self.timelineTable.setAlternatingRowColors(True)
        self.timelineTable.setObjectName("timelineTable")
        self.timelineTable.setColumnCount(4)
        self.timelineTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.timelineTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timelineTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timelineTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timelineTable.setHorizontalHeaderItem(3, item)
        self.vboxlayout3.addWidget(self.timelineTable)
        self.detailTabs.addTab(self.tabTimeline, "")
        self.centerLayout.addWidget(self.verticalSplitter)
        self.mainLayout.addWidget(self.mainSplitter)
        self.statusBar = QtWidgets.QStatusBar(RegistryAnalysisWidget)
        self.statusBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.statusBar.setObjectName("statusBar")
        self.mainLayout.addWidget(self.statusBar)

        self.retranslateUi(RegistryAnalysisWidget)
        self.detailTabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(RegistryAnalysisWidget)

    def retranslateUi(self, RegistryAnalysisWidget):
        _translate = QtCore.QCoreApplication.translate
        RegistryAnalysisWidget.setWindowTitle(_translate("RegistryAnalysisWidget", "Registry Analysis"))
        self.caseInfoLabel.setText(_translate("RegistryAnalysisWidget", "Case: Not Selected"))
        self.btnLoadSelectedHive.setText(_translate("RegistryAnalysisWidget", "Load Hive"))
        self.btnRefreshHives.setToolTip(_translate("RegistryAnalysisWidget", "Refresh hive list"))
        self.btnRefreshHives.setText(_translate("RegistryAnalysisWidget", "↻"))
        self.statusIndicator.setText(_translate("RegistryAnalysisWidget", "● Ready"))
        self.btnExport.setText(_translate("RegistryAnalysisWidget", "Export ▼"))
        self.btnExpandAll.setToolTip(_translate("RegistryAnalysisWidget", "Expand All"))
        self.btnExpandAll.setText(_translate("RegistryAnalysisWidget", "⊞"))
        self.btnCollapseAll.setToolTip(_translate("RegistryAnalysisWidget", "Collapse All"))
        self.btnCollapseAll.setText(_translate("RegistryAnalysisWidget", "⊟"))
        self.txtTreeFilter.setPlaceholderText(_translate("RegistryAnalysisWidget", "Filter keys..."))
        self.lblPath.setText(_translate("RegistryAnalysisWidget", "Path:"))
        self.btnCopyPath.setToolTip(_translate("RegistryAnalysisWidget", "Copy Path"))
        self.btnCopyPath.setText(_translate("RegistryAnalysisWidget", "📋"))
        self.detailTabs.setTabText(self.detailTabs.indexOf(self.tabHex), _translate("RegistryAnalysisWidget", "Hex View"))
        self.lblFormat.setText(_translate("RegistryAnalysisWidget", "Format:"))
        self.cmbFormat.setItemText(0, _translate("RegistryAnalysisWidget", "Auto-detect"))
        self.cmbFormat.setItemText(1, _translate("RegistryAnalysisWidget", "UTF-16 String"))
        self.cmbFormat.setItemText(2, _translate("RegistryAnalysisWidget", "UTF-8 String"))
        self.cmbFormat.setItemText(3, _translate("RegistryAnalysisWidget", "DWORD (32-bit)"))
        self.cmbFormat.setItemText(4, _translate("RegistryAnalysisWidget", "QWORD (64-bit)"))
        self.cmbFormat.setItemText(5, _translate("RegistryAnalysisWidget", "Windows FILETIME"))
        self.cmbFormat.setItemText(6, _translate("RegistryAnalysisWidget", "Hex Dump"))
        self.detailTabs.setTabText(self.detailTabs.indexOf(self.tabDecoded), _translate("RegistryAnalysisWidget", "Decoded"))
        self.analysisView.setHtml(_translate("RegistryAnalysisWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select a registry key to see forensic analysis...</p></body></html>"))
        self.detailTabs.setTabText(self.detailTabs.indexOf(self.tabAnalysis), _translate("RegistryAnalysisWidget", "Analysis"))
        self.timelineTable.setSortingEnabled(True)
        item = self.timelineTable.horizontalHeaderItem(0)
        item.setText(_translate("RegistryAnalysisWidget", "Time"))
        item = self.timelineTable.horizontalHeaderItem(1)
        item.setText(_translate("RegistryAnalysisWidget", "Key"))
        item = self.timelineTable.horizontalHeaderItem(2)
        item.setText(_translate("RegistryAnalysisWidget", "Action"))
        item = self.timelineTable.horizontalHeaderItem(3)
        item.setText(_translate("RegistryAnalysisWidget", "Details"))
        self.detailTabs.setTabText(self.detailTabs.indexOf(self.tabTimeline), _translate("RegistryAnalysisWidget", "Timeline"))
