# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\collect_volatile.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1400, 852)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.mainLayout = QtWidgets.QVBoxLayout(Form)
        self.mainLayout.setContentsMargins(15, 15, 15, 15)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        self.warningLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.warningLabel.setFont(font)
        self.warningLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.warningLabel.setObjectName("warningLabel")
        self.mainLayout.addWidget(self.warningLabel)
        self.mainHorizontalLayout = QtWidgets.QHBoxLayout()
        self.mainHorizontalLayout.setSpacing(15)
        self.mainHorizontalLayout.setObjectName("mainHorizontalLayout")
        self.leftColumnLayout = QtWidgets.QVBoxLayout()
        self.leftColumnLayout.setSpacing(10)
        self.leftColumnLayout.setObjectName("leftColumnLayout")
        self.acquisitionConfigGroup = QtWidgets.QGroupBox(Form)
        self.acquisitionConfigGroup.setMinimumSize(QtCore.QSize(450, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.acquisitionConfigGroup.setFont(font)
        self.acquisitionConfigGroup.setObjectName("acquisitionConfigGroup")
        self.configLayout = QtWidgets.QVBoxLayout(self.acquisitionConfigGroup)
        self.configLayout.setSpacing(8)
        self.configLayout.setObjectName("configLayout")
        self.targetSystemLayout = QtWidgets.QHBoxLayout()
        self.targetSystemLayout.setObjectName("targetSystemLayout")
        self.configLayout.addLayout(self.targetSystemLayout)
        self.caseInfoLayout = QtWidgets.QHBoxLayout()
        self.caseInfoLayout.setObjectName("caseInfoLayout")
        self.caseIdLabel = QtWidgets.QLabel(self.acquisitionConfigGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.caseIdLabel.setFont(font)
        self.caseIdLabel.setObjectName("caseIdLabel")
        self.caseInfoLayout.addWidget(self.caseIdLabel)
        self.caseIdEdit = QtWidgets.QLineEdit(self.acquisitionConfigGroup)
        self.caseIdEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.caseIdEdit.setFont(font)
        self.caseIdEdit.setObjectName("caseIdEdit")
        self.caseInfoLayout.addWidget(self.caseIdEdit)
        self.configLayout.addLayout(self.caseInfoLayout)
        self.outputDeviceLayout = QtWidgets.QHBoxLayout()
        self.outputDeviceLayout.setObjectName("outputDeviceLayout")
        self.outputDeviceLabel = QtWidgets.QLabel(self.acquisitionConfigGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.outputDeviceLabel.setFont(font)
        self.outputDeviceLabel.setObjectName("outputDeviceLabel")
        self.outputDeviceLayout.addWidget(self.outputDeviceLabel)
        self.outputPathEdit = QtWidgets.QLineEdit(self.acquisitionConfigGroup)
        self.outputPathEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.outputPathEdit.setFont(font)
        self.outputPathEdit.setObjectName("outputPathEdit")
        self.outputDeviceLayout.addWidget(self.outputPathEdit)
        self.browseOutputBtn = QtWidgets.QPushButton(self.acquisitionConfigGroup)
        self.browseOutputBtn.setMinimumSize(QtCore.QSize(40, 30))
        self.browseOutputBtn.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.browseOutputBtn.setFont(font)
        self.browseOutputBtn.setObjectName("browseOutputBtn")
        self.outputDeviceLayout.addWidget(self.browseOutputBtn)
        self.configLayout.addLayout(self.outputDeviceLayout)
        self.investigatorLayout = QtWidgets.QHBoxLayout()
        self.investigatorLayout.setObjectName("investigatorLayout")
        self.configLayout.addLayout(self.investigatorLayout)
        self.leftColumnLayout.addWidget(self.acquisitionConfigGroup)
        self.orderOfVolatilityGroup = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.orderOfVolatilityGroup.setFont(font)
        self.orderOfVolatilityGroup.setObjectName("orderOfVolatilityGroup")
        self.volatilityLayout = QtWidgets.QVBoxLayout(self.orderOfVolatilityGroup)
        self.volatilityLayout.setSpacing(5)
        self.volatilityLayout.setObjectName("volatilityLayout")
        self.priorityInfoLabel = QtWidgets.QLabel(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.priorityInfoLabel.setFont(font)
        self.priorityInfoLabel.setObjectName("priorityInfoLabel")
        self.volatilityLayout.addWidget(self.priorityInfoLabel)
        self.ramAcquisitionCheck = QtWidgets.QCheckBox(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ramAcquisitionCheck.setFont(font)
        self.ramAcquisitionCheck.setChecked(True)
        self.ramAcquisitionCheck.setObjectName("ramAcquisitionCheck")
        self.volatilityLayout.addWidget(self.ramAcquisitionCheck)
        self.systemTimeCheck = QtWidgets.QCheckBox(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.systemTimeCheck.setFont(font)
        self.systemTimeCheck.setChecked(True)
        self.systemTimeCheck.setObjectName("systemTimeCheck")
        self.volatilityLayout.addWidget(self.systemTimeCheck)
        self.networkStateCheck = QtWidgets.QCheckBox(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.networkStateCheck.setFont(font)
        self.networkStateCheck.setChecked(True)
        self.networkStateCheck.setObjectName("networkStateCheck")
        self.volatilityLayout.addWidget(self.networkStateCheck)
        self.processInfoCheck = QtWidgets.QCheckBox(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.processInfoCheck.setFont(font)
        self.processInfoCheck.setChecked(True)
        self.processInfoCheck.setObjectName("processInfoCheck")
        self.volatilityLayout.addWidget(self.processInfoCheck)
        self.userSessionsCheck = QtWidgets.QCheckBox(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.userSessionsCheck.setFont(font)
        self.userSessionsCheck.setChecked(True)
        self.userSessionsCheck.setObjectName("userSessionsCheck")
        self.volatilityLayout.addWidget(self.userSessionsCheck)
        self.clipboardCheck = QtWidgets.QCheckBox(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clipboardCheck.setFont(font)
        self.clipboardCheck.setChecked(True)
        self.clipboardCheck.setObjectName("clipboardCheck")
        self.volatilityLayout.addWidget(self.clipboardCheck)
        self.commandHistoryCheck = QtWidgets.QCheckBox(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.commandHistoryCheck.setFont(font)
        self.commandHistoryCheck.setChecked(True)
        self.commandHistoryCheck.setObjectName("commandHistoryCheck")
        self.volatilityLayout.addWidget(self.commandHistoryCheck)
        self.servicesDriversCheck = QtWidgets.QCheckBox(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.servicesDriversCheck.setFont(font)
        self.servicesDriversCheck.setChecked(True)
        self.servicesDriversCheck.setObjectName("servicesDriversCheck")
        self.volatilityLayout.addWidget(self.servicesDriversCheck)
        self.environmentVarsCheck = QtWidgets.QCheckBox(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.environmentVarsCheck.setFont(font)
        self.environmentVarsCheck.setChecked(False)
        self.environmentVarsCheck.setObjectName("environmentVarsCheck")
        self.volatilityLayout.addWidget(self.environmentVarsCheck)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.volatilityLayout.addItem(spacerItem)
        self.volatilityButtonsLayout = QtWidgets.QHBoxLayout()
        self.volatilityButtonsLayout.setObjectName("volatilityButtonsLayout")
        self.selectAllBtn = QtWidgets.QPushButton(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.selectAllBtn.setFont(font)
        self.selectAllBtn.setObjectName("selectAllBtn")
        self.volatilityButtonsLayout.addWidget(self.selectAllBtn)
        self.clearAllBtn = QtWidgets.QPushButton(self.orderOfVolatilityGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.clearAllBtn.setFont(font)
        self.clearAllBtn.setObjectName("clearAllBtn")
        self.volatilityButtonsLayout.addWidget(self.clearAllBtn)
        self.volatilityLayout.addLayout(self.volatilityButtonsLayout)
        self.leftColumnLayout.addWidget(self.orderOfVolatilityGroup)
        self.ramConfigGroup = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ramConfigGroup.setFont(font)
        self.ramConfigGroup.setObjectName("ramConfigGroup")
        self.ramConfigLayout = QtWidgets.QVBoxLayout(self.ramConfigGroup)
        self.ramConfigLayout.setObjectName("ramConfigLayout")
        self.ramFormatLayout = QtWidgets.QHBoxLayout()
        self.ramFormatLayout.setObjectName("ramFormatLayout")
        self.ramFormatLabel = QtWidgets.QLabel(self.ramConfigGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ramFormatLabel.setFont(font)
        self.ramFormatLabel.setObjectName("ramFormatLabel")
        self.ramFormatLayout.addWidget(self.ramFormatLabel)
        self.ramFormatCombo = QtWidgets.QComboBox(self.ramConfigGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ramFormatCombo.setFont(font)
        self.ramFormatCombo.setObjectName("ramFormatCombo")
        self.ramFormatCombo.addItem("")
        self.ramFormatCombo.addItem("")
        self.ramFormatCombo.addItem("")
        self.ramFormatLayout.addWidget(self.ramFormatCombo)
        self.ramConfigLayout.addLayout(self.ramFormatLayout)
        self.calculateHashCheck = QtWidgets.QCheckBox(self.ramConfigGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.calculateHashCheck.setFont(font)
        self.calculateHashCheck.setChecked(True)
        self.calculateHashCheck.setObjectName("calculateHashCheck")
        self.ramConfigLayout.addWidget(self.calculateHashCheck)
        self.compressRamCheck = QtWidgets.QCheckBox(self.ramConfigGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.compressRamCheck.setFont(font)
        self.compressRamCheck.setChecked(False)
        self.compressRamCheck.setObjectName("compressRamCheck")
        self.ramConfigLayout.addWidget(self.compressRamCheck)
        self.leftColumnLayout.addWidget(self.ramConfigGroup)
        self.startCollectionBtn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.startCollectionBtn.setFont(font)
        self.startCollectionBtn.setObjectName("startCollectionBtn")
        self.leftColumnLayout.addWidget(self.startCollectionBtn)
        self.mainHorizontalLayout.addLayout(self.leftColumnLayout)
        self.rightColumnLayout = QtWidgets.QVBoxLayout()
        self.rightColumnLayout.setSpacing(10)
        self.rightColumnLayout.setObjectName("rightColumnLayout")
        self.systemInfoGroup = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.systemInfoGroup.setFont(font)
        self.systemInfoGroup.setObjectName("systemInfoGroup")
        self.systemInfoLayout = QtWidgets.QVBoxLayout(self.systemInfoGroup)
        self.systemInfoLayout.setObjectName("systemInfoLayout")
        self.systemInfoText = QtWidgets.QTextEdit(self.systemInfoGroup)
        font = QtGui.QFont()
        font.setFamily("Consolas,monospace")
        font.setPointSize(-1)
        self.systemInfoText.setFont(font)
        self.systemInfoText.setStyleSheet("font-size: 14px;")
        self.systemInfoText.setReadOnly(True)
        self.systemInfoText.setObjectName("systemInfoText")
        self.systemInfoLayout.addWidget(self.systemInfoText)
        self.rightColumnLayout.addWidget(self.systemInfoGroup)
        self.progressGroup = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.progressGroup.setFont(font)
        self.progressGroup.setObjectName("progressGroup")
        self.progressLayout = QtWidgets.QVBoxLayout(self.progressGroup)
        self.progressLayout.setSpacing(8)
        self.progressLayout.setObjectName("progressLayout")
        self.currentTaskLabel = QtWidgets.QLabel(self.progressGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.currentTaskLabel.setFont(font)
        self.currentTaskLabel.setObjectName("currentTaskLabel")
        self.progressLayout.addWidget(self.currentTaskLabel)
        self.overallProgressBar = QtWidgets.QProgressBar(self.progressGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.overallProgressBar.setFont(font)
        self.overallProgressBar.setProperty("value", 0)
        self.overallProgressBar.setObjectName("overallProgressBar")
        self.progressLayout.addWidget(self.overallProgressBar)
        self.taskDetailLabel = QtWidgets.QLabel(self.progressGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.taskDetailLabel.setFont(font)
        self.taskDetailLabel.setObjectName("taskDetailLabel")
        self.progressLayout.addWidget(self.taskDetailLabel)
        self.taskProgressBar = QtWidgets.QProgressBar(self.progressGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.taskProgressBar.setFont(font)
        self.taskProgressBar.setProperty("value", 0)
        self.taskProgressBar.setObjectName("taskProgressBar")
        self.progressLayout.addWidget(self.taskProgressBar)
        self.timeInfoLayout = QtWidgets.QHBoxLayout()
        self.timeInfoLayout.setObjectName("timeInfoLayout")
        self.elapsedTimeLabel = QtWidgets.QLabel(self.progressGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.elapsedTimeLabel.setFont(font)
        self.elapsedTimeLabel.setObjectName("elapsedTimeLabel")
        self.timeInfoLayout.addWidget(self.elapsedTimeLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.timeInfoLayout.addItem(spacerItem1)
        self.etaLabel = QtWidgets.QLabel(self.progressGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.etaLabel.setFont(font)
        self.etaLabel.setObjectName("etaLabel")
        self.timeInfoLayout.addWidget(self.etaLabel)
        self.progressLayout.addLayout(self.timeInfoLayout)
        self.ramSizeLabel = QtWidgets.QLabel(self.progressGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ramSizeLabel.setFont(font)
        self.ramSizeLabel.setObjectName("ramSizeLabel")
        self.progressLayout.addWidget(self.ramSizeLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.progressLayout.addItem(spacerItem2)
        self.rightColumnLayout.addWidget(self.progressGroup)
        self.evidenceLogGroup = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.evidenceLogGroup.setFont(font)
        self.evidenceLogGroup.setObjectName("evidenceLogGroup")
        self.evidenceLogLayout = QtWidgets.QVBoxLayout(self.evidenceLogGroup)
        self.evidenceLogLayout.setSpacing(8)
        self.evidenceLogLayout.setObjectName("evidenceLogLayout")
        self.evidenceLogText = QtWidgets.QTextEdit(self.evidenceLogGroup)
        font = QtGui.QFont()
        font.setFamily("Consolas,monospace")
        font.setPointSize(-1)
        self.evidenceLogText.setFont(font)
        self.evidenceLogText.setStyleSheet("font-size: 14px;")
        self.evidenceLogText.setReadOnly(True)
        self.evidenceLogText.setObjectName("evidenceLogText")
        self.evidenceLogLayout.addWidget(self.evidenceLogText)
        self.evidenceControlLayout = QtWidgets.QHBoxLayout()
        self.evidenceControlLayout.setObjectName("evidenceControlLayout")
        self.clearLogBtn = QtWidgets.QPushButton(self.evidenceLogGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.clearLogBtn.setFont(font)
        self.clearLogBtn.setObjectName("clearLogBtn")
        self.evidenceControlLayout.addWidget(self.clearLogBtn)
        self.saveLogBtn = QtWidgets.QPushButton(self.evidenceLogGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.saveLogBtn.setFont(font)
        self.saveLogBtn.setObjectName("saveLogBtn")
        self.evidenceControlLayout.addWidget(self.saveLogBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.evidenceControlLayout.addItem(spacerItem3)
        self.stopCollectionBtn = QtWidgets.QPushButton(self.evidenceLogGroup)
        self.stopCollectionBtn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.stopCollectionBtn.setFont(font)
        self.stopCollectionBtn.setObjectName("stopCollectionBtn")
        self.evidenceControlLayout.addWidget(self.stopCollectionBtn)
        self.evidenceLogLayout.addLayout(self.evidenceControlLayout)
        self.rightColumnLayout.addWidget(self.evidenceLogGroup)
        self.mainHorizontalLayout.addLayout(self.rightColumnLayout)
        self.mainLayout.addLayout(self.mainHorizontalLayout)

        self.retranslateUi(Form)
        self.ramFormatCombo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Thu thập dữ liệu khả biến - Forensic Live Collection"))
        Form.setStyleSheet(_translate("Form", "QWidget {\n"
"    background-color: #f8f9fa;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 8px;\n"
"    margin-top: 1ex;\n"
"    padding-top: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 8px 0 8px;\n"
"    color: #495057;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #6c757d;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 1px solid #dee2e6;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    background-color: #e9ecef;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #28a745;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    background-color: white;\n"
"    font-family: \'Consolas\', monospace;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #495057;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #495057;\n"
"    spacing: 8px;\n"
"}"))
        self.titleLabel.setStyleSheet(_translate("Form", "color: #dc3545; padding: 10px; background-color: #fff5f5; border: 2px solid #dc3545; border-radius: 8px;"))
        self.titleLabel.setText(_translate("Form", "🚨 FORENSIC LIVE COLLECTION - Thu thập Dữ liệu Khả biến"))
        self.warningLabel.setStyleSheet(_translate("Form", "background-color: #fff3cd; color: #856404; padding: 8px; border: 1px solid #ffeaa7; border-radius: 4px; font-weight: bold;"))
        self.warningLabel.setText(_translate("Form", "⚠️  CẢNH BÁO: Thu thập theo \"Order of Volatility\" - Dữ liệu RAM ưu tiên cao nhất. Chạy từ thiết bị ngoài để tối thiểu tác động!"))
        self.acquisitionConfigGroup.setTitle(_translate("Form", "🔧 Cấu hình Thu thập"))
        self.caseIdLabel.setText(_translate("Form", "📋 Case name:"))
        self.caseIdEdit.setPlaceholderText(_translate("Form", "VD: Điều tra máy tính A"))
        self.outputDeviceLabel.setText(_translate("Form", "💾 Thiết bị lưu trữ:"))
        self.outputPathEdit.setText(_translate("Form", "E:\\ForensicCollection"))
        self.outputPathEdit.setPlaceholderText(_translate("Form", "Chọn thiết bị ngoài (USB/External HDD)"))
        self.browseOutputBtn.setText(_translate("Form", "📁"))
        self.orderOfVolatilityGroup.setTitle(_translate("Form", "📊 Order of Volatility - Thứ tự thu thập"))
        self.priorityInfoLabel.setText(_translate("Form", "Thứ tự ưu tiên từ cao đến thấp (càng lên trên càng dễ mất):"))
        self.ramAcquisitionCheck.setStyleSheet(_translate("Form", "color: #dc3545; font-weight: bold;"))
        self.ramAcquisitionCheck.setText(_translate("Form", "🥇 1. RAM Acquisition (Bộ nhớ vật lý - Ưu tiên cao nhất)"))
        self.systemTimeCheck.setText(_translate("Form", "🥈 2. System Time & Uptime (Thời gian hệ thống)"))
        self.networkStateCheck.setText(_translate("Form", "🥉 3. Network State (Kết nối mạng đang hoạt động)"))
        self.processInfoCheck.setText(_translate("Form", "🏅 4. Process Information (Tiến trình đang chạy)"))
        self.userSessionsCheck.setText(_translate("Form", "🏅 5. User Sessions (Phiên đăng nhập)"))
        self.clipboardCheck.setText(_translate("Form", "📎 6. Clipboard Content (Nội dung clipboard)"))
        self.commandHistoryCheck.setText(_translate("Form", "📝 7. Command History (Lịch sử lệnh)"))
        self.servicesDriversCheck.setText(_translate("Form", "⚙️ 8. Services & Drivers (Dịch vụ & Trình điều khiển)"))
        self.environmentVarsCheck.setText(_translate("Form", "🌍 9. Environment Variables (Biến môi trường)"))
        self.selectAllBtn.setText(_translate("Form", "✅ Chọn tất cả"))
        self.clearAllBtn.setText(_translate("Form", "❌ Bỏ chọn tất cả"))
        self.ramConfigGroup.setTitle(_translate("Form", "🧠 Cấu hình RAM Acquisition"))
        self.ramFormatLabel.setText(_translate("Form", "📄 Định dạng:"))
        self.ramFormatCombo.setItemText(0, _translate("Form", "RAW (.mem) - Tiêu chuẩn"))
        self.ramFormatCombo.setItemText(1, _translate("Form", "RAW (.raw) - Tương thích rộng"))
        self.ramFormatCombo.setItemText(2, _translate("Form", "AFF4 (.aff4) - Nén & Metadata"))
        self.calculateHashCheck.setText(_translate("Form", "🔐 Tính toán Hash SHA-256 trong quá trình thu thập"))
        self.compressRamCheck.setText(_translate("Form", "🗜️ Nén RAM dump (tiết kiệm không gian)"))
        self.startCollectionBtn.setStyleSheet(_translate("Form", "QPushButton {\n"
"    background-color: #dc3545;\n"
"    font-size: 16px;\n"
"    border: 2px solid #bd2130;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c82333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #bd2130;\n"
"}"))
        self.startCollectionBtn.setText(_translate("Form", "🚀 BẮT ĐẦU THU THẬP"))
        self.systemInfoGroup.setTitle(_translate("Form", "💻 Thông tin Hệ thống"))
        self.systemInfoText.setPlaceholderText(_translate("Form", "Thông tin hệ thống sẽ hiển thị ở đây..."))
        self.progressGroup.setTitle(_translate("Form", "📊 Tiến trình Thu thập"))
        self.currentTaskLabel.setText(_translate("Form", "Trạng thái: Sẵn sàng thu thập"))
        self.overallProgressBar.setFormat(_translate("Form", "Tổng tiến trình: %p%"))
        self.taskDetailLabel.setText(_translate("Form", "Chi tiết: Chưa bắt đầu"))
        self.taskProgressBar.setFormat(_translate("Form", "Tác vụ hiện tại: %p%"))
        self.elapsedTimeLabel.setText(_translate("Form", "⏱️ Thời gian: 00:00:00"))
        self.etaLabel.setText(_translate("Form", "📅 ETA: --:--:--"))
        self.ramSizeLabel.setText(_translate("Form", "🧠 RAM: -- GB | 💾 Cần: -- GB | 📦 Gói: -- MB"))
        self.evidenceLogGroup.setTitle(_translate("Form", "📋 Evidence Log & Chain of Custody"))
        self.evidenceLogText.setPlaceholderText(_translate("Form", "Evidence log và chain of custody sẽ được ghi ở đây..."))
        self.clearLogBtn.setText(_translate("Form", "🗑️ Xóa log"))
        self.saveLogBtn.setText(_translate("Form", "💾 Lưu log"))
        self.stopCollectionBtn.setStyleSheet(_translate("Form", "QPushButton {\n"
"    background-color: #dc3545;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c82333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #bd2130;\n"
"}"))
        self.stopCollectionBtn.setText(_translate("Form", "⏹️ DỪNG THU THẬP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
